Flank/flank-dashboard

metrics/lib/features/dashboard/presentation/widgets/circle_percentage.dart

CirclePercentage widget documentation

---

analysis_options.yaml
guardian/analysis_options.yaml
metrics/analysis_options.yaml

Lint package configuration 

---

docs/02_process.md
metrics/test_driver/common/arguments/driver_tests_parser.dart
metrics/test_driver/common/command/drive_command.dart
metrics/test_driver/common/command/run_command.dart
metrics/test_driver/common/config/browser_name.dart
metrics/test_driver/common/config/device.dart
metrics/test_driver/common/config/driver_tests_config.dart
metrics/test_driver/common/process_manager/process_manager.dart
metrics/test_driver/util/file_utils.dart

Flutter Web Driver tests

---

guardian/bin/main.dart
guardian/build.sh
guardian/test.sh

Setup bitrise build for guardian CLI

---

metrics/lib/features/dashboard/data/repositories/metrics_repository_impl.dart
metrics/lib/features/dashboard/presentation/pages/dashboard_page.dart
metrics/lib/features/dashboard/presentation/widgets/circle_percentage.dart
metrics/lib/features/dashboard/presentation/widgets/expandable_text.dart
metrics/lib/features/dashboard/presentation/widgets/sparkline_graph.dart
metrics/lib/injection_container.dart
metrics/pubspec.yaml
metrics/test/features/dashboard/presentation/page/dashboard_page_test.dart
metrics/test/features/dashboard/presentation/widgets/circle_percentage_test.dart
metrics/test/features/dashboard/presentation/widgets/sparkline_graph_test.dart
metrics/test_driver/app_test.dart
metrics/test_driver/flutter_web_driver.dart

Sparkline Graph widget

---

metrics/lib/features/dashboard/presentation/pages/dashboard_page.dart
metrics/lib/features/dashboard/presentation/widgets/build_result_bar_graph.dart

Reposition of dashboard widgets to be in one line

---

docs/00_template.md
docs/03_third_party_api_testing.md
docs/04_mock_server.md

add third party api testing document

---

shell_words/lib/shell_words.dart
shell_words/lib/src/batch.dart
shell_words/lib/src/parser.dart
shell_words/lib/src/posix.dart
shell_words/lib/src/quote.dart
shell_words/lib/src/split.dart
shell_words/pubspec.yaml
shell_words/test/batch_test.dart
shell_words/test/posix_test.dart

Refactor the code to fix according to effective dart documentation guide.
[Ref]: https://dart.dev/guides/language/effective-dart

shell_words fix

---

shell_words/.gitignore
shell_words/.vscode/launch.json
shell_words/CHANGELOG.md
shell_words/LICENSE
shell_words/README.md
shell_words/analysis_options.yaml
shell_words/lib/shell_words.dart
shell_words/lib/src/batch.dart
shell_words/lib/src/models/parser_result.dart
shell_words/lib/src/parser.dart
shell_words/lib/src/posix.dart
shell_words/lib/src/quote.dart
shell_words/lib/src/split.dart
shell_words/pubspec.yaml
shell_words/test/batch_test.dart
shell_words/test/posix_test.dart
shell_words/tool/main.dart

Fixes #57
Dart port of https://github.com/buildkite/shellwords

Add shell_words

---

metrics/.firebaserc
metrics/.gitignore
metrics/firebase.json

Setup firebase deployment 

---

metrics/lib/features/common/presentation/injector/widget/injection_container.dart
metrics/lib/features/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
metrics/lib/features/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
metrics/lib/features/common/presentation/metrics_theme/widgets/metrics_theme_builder.dart
metrics/lib/features/dashboard/presentation/pages/dashboard_page.dart
metrics/lib/features/dashboard/presentation/strings/dashboard_strings.dart
metrics/lib/features/dashboard/presentation/widgets/bar_graph.dart
metrics/lib/features/dashboard/presentation/widgets/build_result_bar_graph.dart
metrics/lib/features/dashboard/presentation/widgets/circle_percentage.dart
metrics/lib/features/dashboard/presentation/widgets/colored_bar.dart
metrics/lib/features/dashboard/presentation/widgets/coverage_circle_percentage.dart
metrics/lib/features/dashboard/presentation/widgets/sparkline_graph.dart
metrics/lib/main.dart
metrics/test/features/common/presentation/metrics_theme/widget/metrics_theme_builder_test.dart
metrics/test/features/dashboard/presentation/page/dashboard_page_test.dart
metrics/test/features/dashboard/presentation/widgets/bar_graph_test.dart
metrics/test/features/dashboard/presentation/widgets/colored_bar_test.dart
metrics/test_driver/app_test.dart

Make widgets look more like designs

---

metrics/test_driver/common/arguments/driver_tests_parser.dart
metrics/test_driver/common/command/command.dart
metrics/test_driver/common/command/drive_command.dart
metrics/test_driver/common/command/flutter_command.dart
metrics/test_driver/common/command/run_command.dart
metrics/test_driver/common/command/run_command_base.dart
metrics/test_driver/common/process_manager/process_manager.dart
metrics/test_driver/flutter_web_driver.dart

Flutter driver tests script improvements

---

metrics/lib/features/common/presentation/metrics_theme/config/color_config.dart
metrics/lib/features/common/presentation/metrics_theme/model/build_results_theme_data.dart
metrics/lib/features/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
metrics/lib/features/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
metrics/lib/features/common/presentation/metrics_theme/model/metric_widget_theme_data.dart
metrics/lib/features/dashboard/presentation/widgets/build_result_bar_graph.dart
metrics/lib/features/dashboard/presentation/widgets/circle_percentage.dart
metrics/lib/features/dashboard/presentation/widgets/coverage_circle_percentage.dart
metrics/lib/features/dashboard/presentation/widgets/sparkline_graph.dart
metrics/lib/main.dart
metrics/test/features/dashboard/presentation/page/dashboard_page_test.dart

Update light theme to match new designs

---

metrics/lib/features/common/presentation/metrics_theme/config/color_config.dart
metrics/lib/features/common/presentation/metrics_theme/model/build_results_theme_data.dart
metrics/lib/features/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
metrics/lib/features/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
metrics/lib/features/common/presentation/metrics_theme/model/metric_widget_theme_data.dart
metrics/lib/features/dashboard/presentation/widgets/build_result_bar_graph.dart
metrics/lib/features/dashboard/presentation/widgets/circle_percentage.dart
metrics/lib/features/dashboard/presentation/widgets/coverage_circle_percentage.dart
metrics/lib/features/dashboard/presentation/widgets/placeholder_bar.dart
metrics/lib/features/dashboard/presentation/widgets/sparkline_graph.dart
metrics/lib/main.dart
metrics/test/features/dashboard/presentation/page/dashboard_page_test.dart
metrics/test/features/dashboard/presentation/widgets/build_result_bar_graph_test.dart
metrics/test/features/dashboard/presentation/widgets/sparkline_graph_test.dart

Metric widgets improvements

---

guardian/README.md
metrics/README.md

Update project readmes with library info

---

docs/08_jenkins_testing_enviroment.md

Jenkins testing environment

---

metrics/ci_integrations/lib/coverage_json_summary/model/coverage.dart
metrics/ci_integrations/lib/coverage_json_summary/model/coverage_json_summary.dart
metrics/ci_integrations/lib/coverage_json_summary/model/total_covarage_summary.dart
metrics/ci_integrations/test/coverage_json_summary_parser/model/coverage_json_summary_test.dart
metrics/ci_integrations/test/coverage_json_summary_parser/model/coverage_test.dart
metrics/ci_integrations/test/coverage_json_summary_parser/model/total_coverage_summary_test.dart

JSON-summary data models

---

metrics/web/lib/features/dashboard/data/repositories/firestore_metrics_repository.dart
metrics/web/lib/features/dashboard/domain/entities/collections/date_time_set.dart
metrics/web/lib/features/dashboard/domain/entities/metrics/build_number_metric.dart
metrics/web/lib/features/dashboard/domain/entities/metrics/build_result.dart
metrics/web/lib/features/dashboard/domain/entities/metrics/build_result_metric.dart
metrics/web/lib/features/dashboard/domain/entities/metrics/dashboard_project_metrics.dart
metrics/web/lib/features/dashboard/domain/entities/metrics/performance_metric.dart
metrics/web/lib/features/dashboard/domain/repositories/metrics_repository.dart
metrics/web/lib/features/dashboard/domain/usecases/receive_project_metrics_updates.dart
metrics/web/lib/features/dashboard/presentation/model/project_metrics_data.dart
metrics/web/lib/features/dashboard/presentation/state/project_metrics_store.dart
metrics/web/lib/features/dashboard/presentation/strings/dashboard_strings.dart
metrics/web/lib/features/dashboard/presentation/widgets/project_metrics_tile.dart
metrics/web/lib/features/dashboard/presentation/widgets/sparkline_graph.dart
metrics/web/lib/features/dashboard/presentation/widgets/text_metric.dart
metrics/web/test/features/dashboard/domain/entities/collections/date_time_set_test.dart
metrics/web/test/features/dashboard/domain/usecases/receive_build_metrics_updates_test.dart
metrics/web/test/features/dashboard/presentation/page/dashboard_page_test.dart
metrics/web/test/features/dashboard/presentation/state/project_metrics_store_test.dart
metrics/web/test/features/dashboard/presentation/widgets/project_metrics_tile_test.dart
metrics/web/test/features/dashboard/presentation/widgets/sparkline_graph_test.dart
metrics/web/test/features/dashboard/presentation/widgets/text_metric_test.dart
metrics/web/test_driver/app_test.dart

Update metrics dashboard based on new definitions

---

metrics/ci_integrations/lib/jenkins/adapter/jenkins_ci_client_adapter.dart
metrics/ci_integrations/test/ci_integration/ci_integration_test.dart

Jenkins Client fetch limit

---

metrics/ci_integrations/lib/ci_integration/ci_integration.dart
metrics/ci_integrations/lib/firestore/adapter/firestore_storage_client_adapter.dart
metrics/ci_integrations/lib/jenkins/adapter/jenkins_ci_client_adapter.dart
metrics/core/lib/src/data/model/build_data.dart
metrics/core/lib/src/domain/entities/build.dart

Unique firestore document id

---

metrics/ci_integrations/lib/firestore/adapter/firestore_storage_client_adapter.dart
metrics/ci_integrations/lib/firestore/deserializer/build_data_deserializer.dart
metrics/ci_integrations/test/firestore/adapter/firestore_storage_client_adapter_test.dart
metrics/ci_integrations/test/firestore/deserializer/build_data_deserializer_test.dart

Implement tests for FirestoreStorageClientAdapter and BuildDataDeserializer

---

docs/10_dart_code_style.md

Dart code style (test description style)

---

metrics/ci_integrations/lib/firestore/adapter/firestore_storage_client_adapter.dart
metrics/ci_integrations/test/firestore/adapter/firestore_storage_client_adapter_test.dart

Async saving error

---

metrics/ci_integrations/lib/integration/interface/destination/client/destination_client.dart
metrics/ci_integrations/lib/integration/interface/source/client/source_client.dart
metrics/ci_integrations/test/integration/ci/config/model/sync_config_test.dart

Some files appear to be imported incorrectly.

[hotfix] Fix CI integrations file imports

---

docs/01_design_doc.md

Update design document with new state management

---

metrics/ci_integrations/config.yaml
metrics/ci_integrations/lib/destination/firestore/client_factory/firestore_destination_client_factory.dart
metrics/ci_integrations/lib/destination/firestore/config/model/firestore_destination_config.dart
metrics/ci_integrations/lib/integration/interface/destination/client/destination_client.dart
metrics/ci_integrations/lib/integration/interface/source/client/source_client.dart
metrics/ci_integrations/test/cli/command/sync_command_test.dart
metrics/ci_integrations/test/cli/test_util/test_data/config_test_data.dart
metrics/ci_integrations/test/destination/firestore/client_factory/firestore_destination_client_factory_test.dart
metrics/ci_integrations/test/destination/firestore/config/model/firestore_destination_config_test.dart
metrics/ci_integrations/test/destination/firestore/config/parser/firestore_destination_config_parser_test.dart
metrics/ci_integrations/test/destination/firestore/test_utils/test_data/firestore_config_test_data.dart
metrics/ci_integrations/test/integration/ci/config/model/sync_config_test.dart

Integrate Firebase Auth into the CI integrations

---

docs/10_dart_code_style.md

Update testing documentation

---

docs/09_firebase_deployment.md

Update firebase deployment document

---

metrics/ci_integrations/.gitignore
metrics/ci_integrations/lib/client/jenkins/model/jenkins_query_limits.dart
metrics/ci_integrations/lib/integration/interface/destination/client/destination_client.dart
metrics/ci_integrations/lib/integration/interface/source/client/source_client.dart
metrics/ci_integrations/lib/source/jenkins/adapter/jenkins_source_client_adapter.dart
metrics/ci_integrations/test/integration/ci/config/model/sync_config_test.dart
metrics/ci_integrations/test/source/jenkins/adapter/jenkins_source_client_adapter_test.dart

Add tests for Jenkins Source Client Adapter

---

metrics/web/docs/01_web_module_architecture.md
metrics/web/docs/02_presentation_layer_architecture.md
metrics/web/docs/03_widget_structure_organization.md

Initial document structure

---

metrics/firebase/firestore/rules/firestore.rules
metrics/firebase/package-lock.json
metrics/firebase/package.json
metrics/firebase/test/firestore/rules/builds-test.js
metrics/firebase/test/firestore/rules/project-groups-test.js
metrics/firebase/test/firestore/rules/test_utils/test-data.js

Project groups security rules

---

metrics/web/docs/03_widget_structure_organization.md

Fix diagram links

---

metrics/web/docs/02_presentation_layer_architecture.md
metrics/web/docs/03_widget_structure_organization.md
metrics/web/docs/diagrams/view_model_usage_class_diagram.puml
metrics/web/docs/diagrams/widget_structure_class_diagram.puml

Presentation layer structure document

---

metrics/web/docs/01_metrics_web_application_architecture.md

Fix links in web application architecture doc

---

docs/02_process.md

Add PR limits and guidelines

---

.github/workflows/web_app_test_and_deploy.yml
.github/workflows/web_app_tests.yml

GitHub actions configuration

---

.github/workflows/web_app_actions.yml

Apply github action trigger to all metrics web application directories

---

metrics/web/lib/base/presentation/widgets/icon_label_button.dart
metrics/web/lib/base/presentation/widgets/padded_card.dart
metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
metrics/web/lib/project_groups/presentation/pages/project_group_page.dart
metrics/web/lib/project_groups/presentation/widgets/add_project_group_card.dart
metrics/web/lib/project_groups/presentation/widgets/project_group_card.dart
metrics/web/lib/project_groups/presentation/widgets/project_group_grid_view.dart
metrics/web/lib/project_groups/presentation/widgets/project_group_view.dart
metrics/web/pubspec.lock
metrics/web/test/base/presentation/widgets/icon_label_button_test.dart
metrics/web/web/icons/add-button.svg

Project Group Card new design

---

metrics/web/lib/common/presentation/injector/widget/injection_container.dart
metrics/web/lib/dashboard/presentation/pages/dashboard_page.dart
metrics/web/lib/dashboard/presentation/state/project_metrics_notifier.dart
metrics/web/test/dashboard/presentation/state/project_metrics_notifier_test.dart
metrics/web/test/test_utils/project_metrics_notifier_stub.dart

Fix project metrics subscriptions

---

metrics/web/lib/common/presentation/models/project_model.dart
metrics/web/test/common/presentation/models/project_model_test.dart
metrics/web/test/common/presentation/state/projects_notifier_test.dart
metrics/web/test/dashboard/presentation/state/project_metrics_notifier_test.dart

add tests for the projects notifier and project model

---

metrics/web/lib/dashboard/presentation/state/project_metrics_notifier.dart
metrics/web/lib/dashboard/presentation/view_models/project_metrics_tile_view_model.dart
metrics/web/lib/dashboard/presentation/widgets/metrics_table.dart
metrics/web/lib/dashboard/presentation/widgets/project_metrics_tile.dart
metrics/web/test/dashboard/presentation/state/project_metrics_notifier_test.dart
metrics/web/test/dashboard/presentation/view_models/project_metrics_tile_view_model_test.dart
metrics/web/test/dashboard/presentation/widgets/project_metrics_tile_test.dart
metrics/web/test/test_utils/project_metrics_notifier_stub.dart

Project metrics tile view model

---

metrics/web/lib/common/presentation/injector/widget/injection_container.dart
metrics/web/lib/dashboard/presentation/state/project_metrics_notifier.dart
metrics/web/lib/project_groups/presentation/state/project_groups_notifier.dart
metrics/web/lib/project_groups/presentation/widgets/add_project_group_card.dart
metrics/web/lib/project_groups/presentation/widgets/delete_project_group_dialog.dart
metrics/web/lib/project_groups/presentation/widgets/project_checkbox_list_tile.dart
metrics/web/lib/project_groups/presentation/widgets/project_group_card.dart
metrics/web/lib/project_groups/presentation/widgets/project_group_dialog.dart
metrics/web/lib/project_groups/presentation/widgets/strategy/edit_project_group_dialog_strategy.dart

Improve view model management in ProjectGroupsNotifier

---

metrics/web/lib/project_groups/presentation/state/project_groups_notifier.dart
metrics/web/lib/project_groups/presentation/view_models/project_checkbox_view_model.dart
metrics/web/lib/project_groups/presentation/view_models/project_group_card_view_model.dart
metrics/web/lib/project_groups/presentation/view_models/project_group_dialog_view_model.dart
metrics/web/lib/project_groups/presentation/widgets/strategy/add_project_group_dialog_strategy.dart
metrics/web/test/project_groups/presentation/widgets/project_group_card_test.dart
metrics/web/test/project_groups/presentation/widgets/strategy/add_project_group_dialog_strategy_test.dart

Make project group view models equatable

---

metrics/web/lib/dashboard/presentation/state/project_metrics_notifier.dart
metrics/web/lib/dashboard/presentation/view_models/build_number_scorecard_view_model.dart
metrics/web/lib/dashboard/presentation/view_models/build_result_metric_view_model.dart
metrics/web/lib/dashboard/presentation/view_models/performance_sparkline_view_model.dart
metrics/web/lib/project_groups/presentation/state/project_groups_notifier.dart
metrics/web/lib/project_groups/presentation/view_models/delete_project_group_dialog_view_model.dart
metrics/web/lib/project_groups/presentation/view_models/project_group_dialog_view_model.dart
metrics/web/test/dashboard/presentation/state/project_metrics_notifier_test.dart
metrics/web/test/dashboard/presentation/view_models/build_result_metric_view_model_test.dart
metrics/web/test/dashboard/presentation/view_models/performance_sparkline_view_model_test.dart
metrics/web/test/dashboard/presentation/view_models/project_metrics_tile_view_model_test.dart
metrics/web/test/dashboard/presentation/widgets/build_result_bar_graph_test.dart
metrics/web/test/dashboard/presentation/widgets/performance_sparkline_graph_test.dart
metrics/web/test/dashboard/presentation/widgets/project_metrics_tile_test.dart
metrics/web/test/project_groups/presentation/widgets/add_project_group_dialog_test.dart
metrics/web/test/project_groups/presentation/widgets/edit_project_group_dialog_test.dart
metrics/web/test/test_utils/project_metrics_notifier_stub.dart

View models immutability improvements

---

metrics/web/lib/common/presentation/app_bar/widget/metrics_app_bar.dart
metrics/web/lib/common/presentation/strings/common_strings.dart
metrics/web/test/common/presentation/app_bar/widget/metrics_app_bar_test.dart
metrics/web/test/common/presentation/widgets/metrics_page_title_test.dart

Add the app icon navigation. Add tests.

---

metrics/web/lib/project_groups/presentation/state/project_groups_notifier.dart
metrics/web/test/project_groups/presentation/state/project_groups_notifier_test.dart

Add tests for project groups notifier

---

docs/09_firebase_deployment.md

Hey, I've tried deploying the metrics application on firebase, without prior experience with flutter and firebase, and I did not encounter any major issues while following the docs, so **nicely done on the docs and setup**!
There were just 2 small inconstancies which are being addressed via this PR.
Since this is a monorepo, it'd be great if nested dependencies would be handled more transparently somehow, as f.e. I've faced issue, where `firebase-functions`  dep was missing when deploying the seed function, due to multiple package.json existing in different directories, each requiring manual `npm install`
Declarative approach to setting up firebase(rather than a detailed step-by-step doc), might be worth trying out (f.e. via terraform) - I can try to PoC that, if you'd be interested.

Minor enhancements to metrics deployment documentation

---

metrics/web/test/project_groups/presentation/pages/project_group_page_test.dart
metrics/web/test/test_utils/metrics_themed_testbed.dart
metrics/web/test/test_utils/projects_notifier_stub.dart

Tests for ProjectGroupsPage class

---

docs/10_dart_code_style.md
metrics/web/docs/03_widget_structure_organization.md

Improve documentation to include the information about immutable classes

---

metrics/web/lib/base/presentation/widgets/dropdown_menu.dart
metrics/web/pubspec.lock
metrics/web/pubspec.yaml
metrics/web/test/base/presentation/widgets/dropdown_menu_test.dart

Add base dropdown menu widget

---

metrics/web/lib/project_groups/presentation/widgets/project_group_view.dart
metrics/web/test/project_groups/presentation/widgets/add_project_group_card_test.dart
metrics/web/test/project_groups/presentation/widgets/project_group_card_test.dart

Tests for project group cards

---

metrics/web/test/base/presentation/widgets/dropdown_body_test.dart
metrics/web/test/base/presentation/widgets/dropdown_item_test.dart

Add tests for base dropdown widgets

---

metrics/web/lib/common/presentation/button/theme/attention_level/metrics_button_attention_level.dart
metrics/web/lib/common/presentation/button/theme/style/metrics_button_style.dart
metrics/web/lib/common/presentation/button/theme/theme_data/metrics_button_theme_data.dart
metrics/web/lib/common/presentation/button/widgets/metrics_button.dart
metrics/web/lib/common/presentation/button/widgets/metrics_negative_button.dart
metrics/web/lib/common/presentation/button/widgets/metrics_neutral_button.dart
metrics/web/lib/common/presentation/button/widgets/metrics_positive_button.dart
metrics/web/lib/common/presentation/metrics_theme/config/color_config.dart
metrics/web/lib/common/presentation/metrics_theme/config/text_style_config.dart
metrics/web/lib/common/presentation/metrics_theme/model/attention_level_theme_data.dart
metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
metrics/web/lib/common/presentation/metrics_theme/model/metrics_theme_data.dart
metrics/web/test/common/presentation/button/theme/attention_level/metrics_button_attention_level_test.dart
metrics/web/test/common/presentation/button/theme/style/metrics_button_style_test.dart
metrics/web/test/common/presentation/button/theme/theme_data/metrics_button_theme_data_test.dart
metrics/web/test/common/presentation/metrics_theme/model/dark_metrics_theme_data_test.dart
metrics/web/test/common/presentation/metrics_theme/model/light_metrics_theme_data_test.dart
metrics/web/test/common/presentation/metrics_theme/model/metrics_theme_data_test.dart

Create reusable Metrics buttons

---

metrics/web/test/dashboard/presentation/page/dashboard_page_test.dart
metrics/web/test/dashboard/presentation/view_models/project_group_dropdown_item_view_model_test.dart
metrics/web/test/dashboard/presentation/widgets/project_groups_dropdown_body_test.dart
metrics/web/test/dashboard/presentation/widgets/project_groups_dropdown_item_test.dart
metrics/web/test/dashboard/presentation/widgets/project_groups_dropdown_menu_test.dart

Add tests for project groups dropdown ui widgets

---

metrics/web/test/common/presentation/button/widgets/metrics_button_test.dart
metrics/web/test/common/presentation/button/widgets/metrics_negative_button_test.dart
metrics/web/test/common/presentation/button/widgets/metrics_neutral_button_test.dart
metrics/web/test/common/presentation/button/widgets/metrics_positive_button_test.dart

Add tests for Metrics buttons

---

metrics/web/lib/dashboard/domain/entities/metrics/dashboard_project_metrics.dart
metrics/web/lib/dashboard/domain/entities/metrics/project_build_status_metric.dart
metrics/web/lib/dashboard/domain/usecases/receive_project_metrics_updates.dart
metrics/web/lib/dashboard/presentation/view_models/build_result_metric_view_model.dart
metrics/web/test/dashboard/domain/entities/metrics/project_build_status_metric_test.dart
metrics/web/test/dashboard/domain/usecases/receive_build_metrics_updates_test.dart
metrics/web/test_driver/app_test.dart
metrics/web/test_driver/common/config/driver_tests_config.dart

Update metrics loading

---

metrics/web/lib/base/presentation/graphs/bar_graph.dart
metrics/web/lib/base/presentation/graphs/placeholder_bar.dart
metrics/web/lib/dashboard/presentation/widgets/build_result_bar.dart
metrics/web/lib/dashboard/presentation/widgets/build_result_bar_graph.dart
metrics/web/lib/dashboard/presentation/widgets/metrics_table_row.dart
metrics/web/test/base/presentation/graphs/placeholder_bar_test.dart
metrics/web/test/dashboard/presentation/widgets/build_result_bar_graph_test.dart

Bar graph and placeholder bar changes

---

metrics/web/lib/common/presentation/metrics_theme/config/color_config.dart
metrics/web/lib/dashboard/presentation/state/project_metrics_notifier.dart
metrics/web/lib/dashboard/presentation/view_models/project_build_status_view_model.dart
metrics/web/lib/dashboard/presentation/view_models/project_metrics_tile_view_model.dart
metrics/web/lib/dashboard/presentation/widgets/metrics_table_header.dart
metrics/web/lib/dashboard/presentation/widgets/metrics_table_row.dart
metrics/web/lib/dashboard/presentation/widgets/project_build_status.dart
metrics/web/lib/dashboard/presentation/widgets/project_metrics_tile.dart
metrics/web/test/dashboard/presentation/state/project_metrics_notifier_test.dart
metrics/web/test/dashboard/presentation/view_models/project_build_status_view_model_test.dart
metrics/web/test/dashboard/presentation/view_models/project_metrics_tile_view_model_test.dart
metrics/web/test/dashboard/presentation/widgets/metrics_table_row_test.dart
metrics/web/test/dashboard/presentation/widgets/project_build_status_test.dart
metrics/web/test/project_groups/presentation/widgets/add_project_group_card_test.dart
metrics/web/test/test_utils/finder_util.dart
metrics/web/web/icons/failed_status.svg
metrics/web/web/icons/successful_status.svg
metrics/web/web/icons/unknown_status.svg

Project build status widget

---

metrics/web/lib/common/presentation/injector/widget/injection_container.dart
metrics/web/lib/dashboard/presentation/state/project_metrics_notifier.dart
metrics/web/lib/dashboard/presentation/widgets/project_groups_dropdown_body.dart
metrics/web/lib/dashboard/presentation/widgets/project_groups_dropdown_item.dart
metrics/web/lib/dashboard/presentation/widgets/project_groups_dropdown_menu.dart
metrics/web/lib/project_groups/presentation/models/project_group_model.dart
metrics/web/lib/project_groups/presentation/pages/project_group_page.dart
metrics/web/lib/project_groups/presentation/state/project_groups_notifier.dart
metrics/web/test/dashboard/presentation/state/project_metrics_notifier_test.dart
metrics/web/test/dashboard/presentation/widgets/project_groups_dropdown_menu_test.dart
metrics/web/test/project_groups/presentation/models/project_group_model_test.dart
metrics/web/test/project_groups/presentation/pages/project_group_page_test.dart
metrics/web/test/project_groups/presentation/state/project_groups_notifier_test.dart
metrics/web/test/test_utils/project_groups_notifier_stub.dart
metrics/web/test/test_utils/project_metrics_notifier_stub.dart

Project group dropdown logic

---

metrics/web/lib/common/presentation/widgets/metrics_checkbox.dart
metrics/web/lib/project_groups/presentation/widgets/project_checkbox_list.dart
metrics/web/lib/project_groups/presentation/widgets/project_checkbox_list_tile.dart
metrics/web/lib/project_groups/presentation/widgets/project_group_dialog.dart
metrics/web/test/common/presentation/widgets/metrics_checkbox_test.dart
metrics/web/test/project_groups/presentation/widgets/project_checkbox_list_test.dart
metrics/web/test/project_groups/presentation/widgets/project_checkbox_list_tile_test.dart
metrics/web/web/icons/check-box-blank.svg
metrics/web/web/icons/check-box.svg

Change projects checkbox list appearance

---

metrics/web/lib/base/presentation/graphs/circle_percentage.dart
metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
metrics/web/lib/dashboard/presentation/widgets/themed_circle_percentage.dart

Improve circle percentage widgets to match new designs

---

metrics/web/lib/common/presentation/strings/common_strings.dart
metrics/web/lib/dashboard/presentation/state/project_metrics_notifier.dart
metrics/web/lib/dashboard/presentation/strings/dashboard_strings.dart
metrics/web/lib/dashboard/presentation/view_models/performance_sparkline_view_model.dart
metrics/web/lib/dashboard/presentation/widgets/performance_sparkline_graph.dart
metrics/web/pubspec.yaml
metrics/web/test/common/presentation/strings/common_strings_test.dart
metrics/web/test/dashboard/presentation/state/project_metrics_notifier_test.dart
metrics/web/test/dashboard/presentation/view_models/performance_sparkline_view_model_test.dart
metrics/web/test/dashboard/presentation/view_models/project_metrics_tile_view_model_test.dart
metrics/web/test/dashboard/presentation/widgets/performance_sparkline_graph_test.dart

Performance sparkline improvements

---

metrics/web/lib/base/presentation/widgets/scorecard.dart
metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
metrics/web/lib/common/presentation/metrics_theme/model/metrics_theme_data.dart
metrics/web/lib/common/presentation/metrics_theme/model/scorecard/theme_data/scorecard_theme_data.dart
metrics/web/lib/dashboard/presentation/widgets/build_number_scorecard.dart
metrics/web/test/common/presentation/metrics_theme/model/dark_metrics_theme_data_test.dart
metrics/web/test/common/presentation/metrics_theme/model/light_metrics_theme_data_test.dart
metrics/web/test/common/presentation/metrics_theme/model/metrics_theme_data_test.dart
metrics/web/test/common/presentation/metrics_theme/model/scorecard/theme_data/scorecard_theme_data_test.dart
metrics/web/test/dashboard/presentation/widgets/build_number_scorecard_test.dart

Create scorecard theme

---

metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
metrics/web/lib/common/presentation/metrics_theme/model/metrics_theme_data.dart
metrics/web/lib/common/presentation/metrics_theme/model/sparkline/theme_data/sparkline_theme_data.dart
metrics/web/lib/dashboard/presentation/widgets/performance_sparkline_graph.dart
metrics/web/test/common/presentation/metrics_theme/model/dark_metrics_theme_data_test.dart
metrics/web/test/common/presentation/metrics_theme/model/light_metrics_theme_data_test.dart
metrics/web/test/common/presentation/metrics_theme/model/metrics_theme_data_test.dart
metrics/web/test/common/presentation/metrics_theme/model/sparkline/theme_data/sparkline_theme_data_test.dart
metrics/web/test/dashboard/presentation/widgets/performance_sparkline_graph_test.dart

Add sparkline theme and apply to the sparkline widget.

---

metrics/web/lib/app.dart
metrics/web/lib/main.dart

Renamed MyApp to MetricsApp

---

metrics/web/lib/base/presentation/graphs/colored_bar.dart
metrics/web/lib/base/presentation/widgets/decorated_container.dart
metrics/web/lib/dashboard/presentation/widgets/project_build_status.dart
metrics/web/lib/dashboard/presentation/widgets/project_groups_dropdown_menu.dart
metrics/web/lib/dashboard/presentation/widgets/project_metrics_tile.dart
metrics/web/lib/project_groups/presentation/widgets/project_checkbox_list_tile.dart
metrics/web/lib/project_groups/presentation/widgets/project_group_dialog.dart
metrics/web/test/base/presentation/graphs/colored_bar_test.dart
metrics/web/test/base/presentation/widgets/decorated_container_test.dart
metrics/web/test/dashboard/presentation/widgets/project_groups_dropdown_menu_test.dart
metrics/web/test/test_utils/finder_util.dart

Create decorated container

---

metrics/web/lib/dashboard/presentation/state/project_metrics_notifier.dart
metrics/web/lib/dashboard/presentation/strings/dashboard_strings.dart
metrics/web/lib/dashboard/presentation/widgets/metrics_table.dart
metrics/web/test/dashboard/presentation/state/project_metrics_notifier_test.dart
metrics/web/test/dashboard/presentation/widgets/metrics_table_test.dart
metrics/web/test/test_utils/project_metrics_notifier_stub.dart
metrics/web/test_driver/app_test.dart

Handled no search results state on Dashboard. Added test for no search results case.

---

metrics/web/lib/dashboard/presentation/widgets/performance_sparkline_graph.dart
metrics/web/test/dashboard/presentation/widgets/performance_sparkline_graph_test.dart

Sparkline graph single build

---

metrics/web/lib/base/presentation/widgets/scorecard.dart
metrics/web/test/base/presentation/widgets/scorecard_test.dart

Added null checks for Scorecard. Fixed tests for null cases in Scorecard tests

---

metrics/web/test/dashboard/presentation/state/project_metrics_notifier_test.dart

Improved async tests in ProjectMetricsNotifier

---

metrics/web/test/project_groups/presentation/widgets/project_group_dialog_test.dart

Add tests for the project group dialog

---

metrics/web/lib/dashboard/presentation/strings/dashboard_strings.dart
metrics/web/lib/dashboard/presentation/widgets/metrics_table.dart
metrics/web/lib/dashboard/presentation/widgets/no_search_results_placeholder.dart
metrics/web/pubspec.lock
metrics/web/test/dashboard/presentation/widgets/metrics_table_test.dart
metrics/web/test/dashboard/presentation/widgets/no_search_results_placeholder_test.dart
metrics/web/test_driver/app_test.dart

Implement NoSearchResultsPlaceholder

---

metrics/web/lib/base/presentation/widgets/shimmer_container.dart
metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
metrics/web/lib/common/presentation/metrics_theme/model/metrics_table/theme_data/project_metrics_table_theme_data.dart
metrics/web/lib/common/presentation/metrics_theme/model/shimmer_placeholder/theme_data/shimmer_placeholder_theme_data.dart
metrics/web/lib/common/presentation/metrics_theme/model/shimmer_placeholder_theme_data.dart
metrics/web/lib/dashboard/domain/entities/metrics/dashboard_project_metrics.dart
metrics/web/lib/dashboard/presentation/state/project_metrics_notifier.dart
metrics/web/lib/dashboard/presentation/widgets/metrics_table.dart
metrics/web/lib/dashboard/presentation/widgets/metrics_table_loading_placeholder.dart
metrics/web/pubspec.yaml
metrics/web/test/base/presentation/widgets/shimmer_container_test.dart
metrics/web/test/common/presentation/metrics_theme/model/metrics_table/theme_data/project_metrics_table_theme_data_test.dart
metrics/web/test/common/presentation/metrics_theme/model/shimmer_placeholder/theme_data/shimmer_placeholder_theme_data_test.dart
metrics/web/test/dashboard/presentation/widgets/metrics_table_loading_placeholder_test.dart
metrics/web/test/dashboard/presentation/widgets/metrics_table_test.dart
metrics/web/test/test_utils/project_metrics_notifier_stub.dart

Metrics table tile loading placeholder

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/workflows/web_app_actions.yml

Fixes #469 - Add issue templates.

chore: Add issue templates

---

.github/workflows/web_app_actions.yml

fix: automatic builds

---

metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
metrics/web/lib/common/presentation/metrics_theme/model/metrics_table/theme_data/project_metrics_table_theme_data.dart
metrics/web/lib/dashboard/presentation/widgets/metrics_table_header.dart
metrics/web/lib/dashboard/presentation/widgets/metrics_table_header_loading_placeholder.dart
metrics/web/lib/dashboard/presentation/widgets/metrics_table_loading_header.dart
metrics/web/lib/dashboard/presentation/widgets/metrics_table_title_header.dart
metrics/web/test/common/presentation/metrics_theme/model/metrics_table/theme_data/project_metrics_table_theme_data_test.dart
metrics/web/test/dashboard/presentation/widgets/metrics_table_header_loading_placeholder_test.dart
metrics/web/test/dashboard/presentation/widgets/metrics_table_header_test.dart
metrics/web/test/dashboard/presentation/widgets/metrics_table_loading_header_test.dart
metrics/web/test/dashboard/presentation/widgets/metrics_table_title_header_test.dart

feat: Metrics table header loading placeholder

---

metrics/web/lib/common/presentation/metrics_theme/config/color_config.dart
metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
metrics/web/lib/common/presentation/metrics_theme/model/metrics_theme_data.dart
metrics/web/lib/common/presentation/widgets/metrics_input_placeholder.dart
metrics/web/lib/dashboard/presentation/pages/dashboard_page.dart
metrics/web/lib/dashboard/presentation/widgets/project_groups_dropdown_menu.dart
metrics/web/lib/dashboard/presentation/widgets/project_metrics_search_input.dart
metrics/web/test/common/presentation/metrics_theme/model/dark_metrics_theme_data_test.dart
metrics/web/test/common/presentation/metrics_theme/model/metrics_theme_data_test.dart
metrics/web/test/common/presentation/widgets/metrics_input_placeholder_test.dart
metrics/web/test/dashboard/presentation/page/dashboard_page_test.dart
metrics/web/test/dashboard/presentation/widgets/project_groups_dropdown_menu_test.dart
metrics/web/test/dashboard/presentation/widgets/project_metrics_search_input_test.dart

feat: Add input loading placeholders

---

.github/workflows/pr_checks.yml
docs/02_process.md

ci: add conventional commits PR checks workflow and documentation

---

metrics/web/lib/dashboard/presentation/widgets/project_groups_dropdown_menu.dart

fix: add single line text to the dropdown menu button

---

metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
metrics/web/lib/common/presentation/metrics_theme/model/user_menu_theme_data.dart
metrics/web/lib/common/presentation/strings/common_strings.dart
metrics/web/lib/common/presentation/toggle/widgets/toggle.dart
metrics/web/lib/common/presentation/widgets/metrics_user_menu_card.dart
metrics/web/test/common/presentation/metrics_theme/model/user_menu_theme_data_test.dart
metrics/web/test/common/presentation/widgets/metrics_user_menu_card_test.dart
metrics/web/test_driver/common/config/driver_tests_config.dart

feat: Implement metrics user menu card

---

metrics/web/test/dashboard/presentation/widgets/project_groups_dropdown_menu_test.dart

test: Add test for single-line text in project group dropdown button

---

metrics/web/lib/project_groups/presentation/pages/project_group_page.dart
metrics/web/lib/project_groups/presentation/strings/project_groups_strings.dart
metrics/web/lib/project_groups/presentation/widgets/delete_project_group_dialog.dart
metrics/web/lib/project_groups/presentation/widgets/project_group_dialog.dart
metrics/web/lib/project_groups/presentation/widgets/strategy/add_project_group_dialog_strategy.dart
metrics/web/lib/project_groups/presentation/widgets/strategy/edit_project_group_dialog_strategy.dart
metrics/web/lib/project_groups/presentation/widgets/strategy/project_group_dialog_strategy.dart
metrics/web/pubspec.yaml
metrics/web/test/project_groups/presentation/pages/project_group_page_test.dart
metrics/web/test/project_groups/presentation/strings/project_groups_strings_test.dart
metrics/web/test/project_groups/presentation/widgets/delete_project_group_dialog_test.dart
metrics/web/test/project_groups/presentation/widgets/project_group_dialog_test.dart
metrics/web/test/project_groups/presentation/widgets/strategy/add_project_group_dialog_strategy_test.dart
metrics/web/test/project_groups/presentation/widgets/strategy/edit_project_group_dialog_strategy_test.dart

feat: Project groups page toasts

---

metrics/web/lib/auth/presentation/pages/login_page.dart
metrics/web/lib/auth/presentation/widgets/auth_form.dart
metrics/web/test/auth/presentation/pages/login_page_test.dart
metrics/web/test/auth/presentation/widgets/auth_form_test.dart

feat: Login page toasts

---

metrics/web/test_driver/common/config/driver_tests_config.dart

fix: Update chromedriver version

---

.github/workflows/web_app_actions.yml

fix: Remove driver tests from the metrics GitHub action

---

.github/workflows/web_app_actions.yml
metrics/web/lib/auth/presentation/pages/loading_page.dart

fix: Enable driver tests and add post frame callback to the loading page

---

metrics/web/lib/dashboard/presentation/pages/dashboard_page.dart
metrics/web/test/dashboard/presentation/page/dashboard_page_test.dart

feat: Show a MetricsToast on each user action/error on the dashboard page

---

metrics/web/lib/project_groups/presentation/widgets/project_checkbox_list_tile.dart

fix: Rendering issue of project groups project list

---

metrics/web/test/common/presentation/metrics_theme/model/add_project_group_card/attention_level/add_project_group_card_attention_level_test.dart
metrics/web/test/common/presentation/metrics_theme/model/add_project_group_card/style/add_project_group_card_style_test.dart
metrics/web/test/common/presentation/metrics_theme/model/add_project_group_card/theme_data/add_project_group_card_theme_data_test.dart

fix: Fix Add Project Group Card test coverage

---

metrics/web/lib/base/presentation/decoration/bubble_shape_border.dart
metrics/web/lib/base/presentation/widgets/tappable_area.dart
metrics/web/lib/common/presentation/toast/widgets/negative_toast.dart
metrics/web/lib/common/presentation/toast/widgets/positive_toast.dart
metrics/web/lib/common/presentation/toast/widgets/toast.dart
metrics/web/lib/project_groups/presentation/widgets/add_project_group_card.dart
metrics/web/lib/project_groups/presentation/widgets/project_group_card.dart
metrics/web/test/base/presentation/widgets/tappable_area_test.dart

fix: Minor documentation and code improvements

---

metrics/firebase/functions/index.js

feat: Email domain validation function

---

metrics/web/lib/base/presentation/widgets/dropdown_item.dart
metrics/web/lib/base/presentation/widgets/tappable_area.dart
metrics/web/lib/common/presentation/dropdown/theme/theme_data/dropdown_item_theme_data.dart
metrics/web/lib/common/presentation/dropdown/widgets/metrics_dropdown_item.dart
metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
metrics/web/test/base/presentation/widgets/dropdown_item_test.dart
metrics/web/test/base/presentation/widgets/tappable_area_test.dart
metrics/web/test/common/presentation/dropdown/theme/theme_data/dropdown_item_theme_data_test.dart

fix: Improve dropdown item hover effect

---

metrics/web/lib/base/presentation/widgets/dropdown_item.dart
metrics/web/test/base/presentation/widgets/dropdown_item_test.dart

fix: Dropdown Item test descritions and readability fixes

---

metrics/web/lib/common/presentation/metrics_theme/config/text_style_config.dart
metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
metrics/web/lib/common/presentation/widgets/metrics_card.dart
metrics/web/lib/common/presentation/widgets/metrics_page_title.dart
metrics/web/lib/common/presentation/widgets/metrics_text_form_field.dart
metrics/web/lib/common/presentation/widgets/metrics_text_style.dart
metrics/web/lib/project_groups/presentation/widgets/add_project_group_card.dart
metrics/web/lib/project_groups/presentation/widgets/project_group_card.dart
metrics/web/test/common/presentation/widgets/metrics_text_form_field_test.dart
metrics/web/test/common/presentation/widgets/metrics_text_style_test.dart

feat: Metrics text style

---

metrics/web/lib/common/presentation/scaffold/widget/metrics_scaffold.dart
metrics/web/test/common/presentation/scaffold/widget/metrics_scaffold_test.dart

fix: Disable drawer edge swipe

---

metrics/web/lib/common/presentation/widgets/metrics_user_menu.dart
metrics/web/test/common/presentation/widgets/metrics_user_menu_test.dart
metrics/web/test/project_groups/presentation/state/project_groups_notifier_test.dart

fix: Remove the user item.

---

metrics/firebase/functions/package-lock.json
metrics/firebase/functions/package.json
metrics/firebase/package-lock.json
metrics/firebase/package.json

fix: Upgrade node-forge version to version 0.10.0 or later

---

metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart

fix: Remove font-weight on the checked checkbox

---

metrics/web/lib/common/presentation/metrics_theme/config/color_config.dart
metrics/web/lib/main.dart
metrics/web/lib/project_groups/presentation/widgets/project_checkbox_list_tile.dart

fix: Remove checkbox selection animation

---

metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
metrics/web/lib/project_groups/presentation/widgets/project_group_dialog.dart
metrics/web/test/project_groups/presentation/widgets/project_group_dialog_test.dart

fix: If user didn't change data on modal dialog - save button should be inactive

---

metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
metrics/web/lib/common/presentation/metrics_theme/model/dialog_theme_data.dart
metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
metrics/web/lib/common/presentation/metrics_theme/model/project_group_dialog_theme_data.dart
metrics/web/lib/project_groups/presentation/widgets/add_project_group_card.dart
metrics/web/lib/project_groups/presentation/widgets/project_group_card.dart
metrics/web/test/common/presentation/metrics_theme/model/dialog_theme_data_test.dart
metrics/web/test/common/presentation/metrics_theme/model/project_group_dialog_theme_data_test.dart
metrics/web/test/project_groups/presentation/widgets/add_project_group_card_test.dart
metrics/web/test/project_groups/presentation/widgets/project_group_card_test.dart

fix: Add backdrop color for dialogs

---

metrics/web/lib/main.dart

fix: Remove modal dialog shadow

---

metrics/web/lib/base/presentation/widgets/icon_label_button.dart
metrics/web/lib/base/presentation/widgets/tappable_area.dart
metrics/web/lib/common/presentation/metrics_theme/config/color_config.dart
metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
metrics/web/lib/common/presentation/metrics_theme/model/project_group_card_theme_data.dart
metrics/web/lib/project_groups/presentation/widgets/project_group_card.dart
metrics/web/test/base/presentation/widgets/icon_label_button_test.dart
metrics/web/test/base/presentation/widgets/tappable_area_test.dart
metrics/web/test/common/presentation/metrics_theme/model/metrics_theme_data_test.dart
metrics/web/test/common/presentation/metrics_theme/model/project_group_card_theme_data_test.dart
metrics/web/test/project_groups/presentation/widgets/project_group_card_test.dart

fix: Icon buttons on hover state should be a bit darker

---

metrics/firebase/functions/package.json
metrics/web/lib/auth/presentation/models/auth_error_message.dart
metrics/web/lib/auth/presentation/strings/auth_strings.dart
metrics/web/test/auth/presentation/models/auth_error_message_test.dart
metrics/web/web/index.html

fix: Email domain validation error message and google sign-in pop-up

---

metrics/web/lib/common/presentation/widgets/metrics_checkbox.dart
metrics/web/lib/project_groups/presentation/widgets/project_checkbox_list_tile.dart
metrics/web/test/common/presentation/widgets/metrics_checkbox_test.dart
metrics/web/test/project_groups/presentation/widgets/project_checkbox_list_tile_test.dart
metrics/web/web/icons/check-box-blank-hovered.svg
metrics/web/web/icons/check-box-hovered.svg

fix: Improve checkbox to apply the hover effect like on the designs.

---

metrics/web/lib/common/presentation/button/theme/style/metrics_button_style.dart
metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
metrics/web/lib/common/presentation/widgets/metrics_checkbox.dart
metrics/web/test/common/presentation/button/theme/style/metrics_button_style_test.dart

fix: Remove button shadows

---

metrics/web/lib/common/presentation/widgets/metrics_scroll_behavior.dart
metrics/web/lib/main.dart

fix: Remove an additional scroll stretching effect

---

metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
metrics/web/lib/common/presentation/metrics_theme/model/metrics_table/theme_data/project_metrics_tile_theme_data.dart
metrics/web/lib/dashboard/presentation/widgets/project_metrics_tile.dart
metrics/web/test/common/presentation/metrics_theme/model/metrics_table/theme_data/project_metrics_tile_theme_data_test.dart
metrics/web/test/dashboard/presentation/widgets/project_metrics_tile_test.dart

fix: Implement hover state for Metrics Project Tile

---

metrics/web/lib/base/presentation/widgets/info_dialog.dart
metrics/web/test/base/presentation/widgets/icon_label_button_test.dart
metrics/web/test/base/presentation/widgets/info_dialog_test.dart
metrics/web/test/project_groups/presentation/widgets/add_project_group_card_test.dart

fix: Improve mouse cursors on Metrics elements

---

metrics/web/lib/project_groups/presentation/widgets/project_checkbox_list_tile.dart
metrics/web/test/project_groups/presentation/widgets/project_checkbox_list_tile_test.dart

fix: Fix checkbox tile pointer

---

metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
metrics/web/lib/common/presentation/strings/common_strings.dart
metrics/web/lib/common/presentation/user_menu_button/theme/user_menu_button_theme_data.dart
metrics/web/lib/common/presentation/user_menu_button/widgets/metrics_user_menu_button.dart
metrics/web/lib/common/presentation/widgets/metrics_text_form_field.dart
metrics/web/test/common/presentation/metrics_theme/model/metrics_theme_data_test.dart
metrics/web/test/common/presentation/user_menu_button/theme/user_menu_button_theme_test.dart
metrics/web/test/common/presentation/user_menu_button/widgets/metrics_user_menu_button_test.dart
metrics/web/test/common/presentation/widgets/metrics_text_form_field_test.dart
metrics/web/test/project_groups/presentation/widgets/project_group_dialog_test.dart

fix: Improve Light theme for the Dashboard Page

---

metrics/web/lib/auth/presentation/pages/login_page.dart
metrics/web/lib/common/presentation/injector/widget/injection_container.dart
metrics/web/lib/common/presentation/metrics_theme/state/theme_notifier.dart
metrics/web/lib/common/presentation/routes/route_generator.dart
metrics/web/test/auth/presentation/pages/login_page_test.dart
metrics/web/test/common/presentation/injector/widget/injection_container_test.dart
metrics/web/test/common/presentation/metrics_theme/state/theme_notifier_test.dart

feat: Login Page theme matches OS theme

---

metrics/web/lib/dashboard/presentation/widgets/metrics_table.dart

fix: Add empty space after last element on the dashboard

---

.github/workflows/web_app_actions.yml
docs/09_firebase_deployment.md
docs/14_firebase_deployment_cli.md
metrics/web/README.md
metrics/web/lib/auth/presentation/pages/loading_page.dart
metrics/web/lib/base/presentation/graphs/circle_percentage.dart
metrics/web/lib/base/presentation/widgets/value_form_field.dart
metrics/web/lib/project_groups/presentation/widgets/project_group_dialog.dart
metrics/web/test/base/presentation/widgets/value_form_field_test.dart

build: Update Flutter version to the latest beta

---

metrics/web/lib/base/presentation/widgets/dropdown_body.dart
metrics/web/lib/dashboard/presentation/widgets/project_groups_dropdown_body.dart
metrics/web/test/base/presentation/widgets/dropdown_body_test.dart
metrics/web/test/dashboard/presentation/widgets/project_groups_dropdown_body_test.dart

fix: Improve Project Groups Dropdown animation

---

metrics/web/pubspec.yaml
metrics/web/test/common/presentation/toggle/widgets/toggle_test.dart

fix: Fix theme toggle switches its value on hover

---

metrics/web/lib/auth/data/repositories/firebase_user_repository.dart
metrics/web/lib/auth/domain/entities/theme_type.dart
metrics/web/lib/auth/domain/entities/user_profile.dart
metrics/web/lib/auth/domain/repositories/user_repository.dart
metrics/web/lib/auth/domain/usecases/create_user_profile_usecase.dart
metrics/web/lib/auth/domain/usecases/parameters/user_id_param.dart
metrics/web/lib/auth/domain/usecases/parameters/user_profile_param.dart
metrics/web/lib/auth/domain/usecases/receive_user_profile_updates.dart
metrics/web/lib/auth/domain/usecases/update_user_profile_usecase.dart
metrics/web/test/auth/domain/entities/user_profile_test.dart
metrics/web/test/auth/domain/usercases/create_user_profile_usecase_test.dart
metrics/web/test/auth/domain/usercases/params/user_id_param_test.dart
metrics/web/test/auth/domain/usercases/params/user_profile_param_test.dart
metrics/web/test/auth/domain/usercases/receive_user_profile_updates_test.dart
metrics/web/test/auth/domain/usercases/update_user_profile_usecase_test.dart

feat: User profile domain layer

---

metrics/web/lib/base/presentation/widgets/info_dialog.dart
metrics/web/lib/project_groups/presentation/widgets/delete_project_group_dialog.dart
metrics/web/lib/project_groups/presentation/widgets/project_group_dialog.dart
metrics/web/test/base/presentation/widgets/info_dialog_test.dart

fix: Long project group name padding

---

metrics/web/lib/auth/data/model/user_profile_data.dart
metrics/web/lib/auth/data/repositories/firebase_user_repository.dart
metrics/web/test/auth/data/model/user_profile_data_test.dart

feat: User profile data

---

metrics/web/lib/auth/presentation/state/auth_notifier.dart
metrics/web/lib/auth/presentation/widgets/auth_form.dart
metrics/web/lib/common/presentation/widgets/metrics_text_form_field.dart
metrics/web/lib/main.dart
metrics/web/test/auth/presentation/state/auth_notifier_test.dart
metrics/web/test/auth/presentation/widgets/auth_form_test.dart
metrics/web/test/common/presentation/widgets/metrics_text_form_field_test.dart
metrics/web/test/test_utils/auth_notifier_stub.dart
metrics/web/test/test_utils/signed_in_auth_notifier_stub.dart

fix: Display error messages near input fields

---

.github/workflows/firebase_actions.yml

feat: Deploy firebase security rules using Github Actions

---

metrics/web/lib/project_groups/presentation/widgets/project_group_dialog.dart
metrics/web/test/project_groups/presentation/widgets/project_group_dialog_test.dart

fix: Fix Project Group Dialog NoSuchMethodException on close

---

metrics/ci_integrations/lib/client/github_actions/mappers/run_conclusion_mapper.dart
metrics/ci_integrations/lib/client/github_actions/mappers/run_status_mapper.dart
metrics/ci_integrations/lib/client/github_actions/models/run_conclusion.dart
metrics/ci_integrations/lib/client/github_actions/models/run_status.dart
metrics/ci_integrations/lib/client/jenkins/mapper/jenkins_build_result_mapper.dart
metrics/ci_integrations/lib/integration/interface/base/client/mapper/mapper.dart
metrics/ci_integrations/test/client/github_actions/mappers/run_conclusion_mapper_test.dart
metrics/ci_integrations/test/client/github_actions/mappers/run_status_mapper_test.dart

ci: Implement GitHub Actions RunStatus, RunConclusion mappers

---

metrics/web/docs/features/user_profile_theme/01_user_profile_theme_design.md

fix: Fix diagram links in user profile theme design document

---

metrics/web/lib/base/presentation/graphs/circle_percentage.dart
metrics/web/test/base/presentation/graphs/circle_percentage_test.dart

fix: Circle percentage widget with null value

---

metrics/web/lib/dashboard/domain/usecases/receive_project_metrics_updates.dart
metrics/web/lib/dashboard/presentation/state/project_metrics_notifier.dart
metrics/web/test/dashboard/domain/usecases/receive_build_metrics_updates_test.dart
metrics/web/test/dashboard/presentation/state/project_metrics_notifier_test.dart

feat: Performance chart group data by day.

---

metrics/web/lib/base/presentation/widgets/keyboard_shortcuts.dart

fix: Disable "Space" hotkey for the fps monitor.

---

metrics/ci_integrations/lib/client/github_actions/models/workflow_run.dart
metrics/ci_integrations/lib/client/github_actions/models/workflow_run_artifact.dart
metrics/ci_integrations/lib/client/github_actions/models/workflow_run_duration.dart
metrics/ci_integrations/test/client/github_actions/models/workflow_run_artifact_test.dart
metrics/ci_integrations/test/client/github_actions/models/workflow_run_duration_test.dart
metrics/ci_integrations/test/client/github_actions/models/workflow_run_test.dart

ci: Implement WorkflowRun, WorkflowRunDuration, WorkflowRunArtifact models

---

docs/09_firebase_deployment.md
docs/15_developer_configuration.md
readme.md

docs: Improve documentation to include supported browsers and run instructions

---

metrics/web/lib/base/presentation/graphs/sparkline_graph.dart
metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
metrics/web/test/base/presentation/graphs/sparkline_graph_test.dart

fix: Make Sparkline more smooth

---

metrics/web/lib/common/presentation/metrics_theme/config/text_style_config.dart
metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
metrics/web/lib/common/presentation/metrics_theme/model/metrics_text/style/metrics_text_style.dart
metrics/web/test/common/presentation/metrics_theme/model/metrics_text/style/metrics_text_style_test.dart

fix: Move metrics text style to an appropriate package

---

metrics/ci_integrations/docs/github_actions/01_github_actions_client.md
metrics/ci_integrations/docs/github_actions/diagrams/github_actions_client_class_diagram.puml

docs: Improve GitHub Actions document

---

metrics/web/lib/base/presentation/graphs/bar_graph.dart
metrics/web/lib/dashboard/presentation/widgets/build_result_bar.dart
metrics/web/lib/dashboard/presentation/widgets/build_result_bar_graph.dart
metrics/web/lib/dashboard/presentation/widgets/strategy/build_result_bar_padding_strategy.dart
metrics/web/lib/main.dart
metrics/web/pubspec.yaml
metrics/web/test/base/presentation/graphs/bar_graph_test.dart
metrics/web/test/dashboard/presentation/widgets/build_result_bar_graph_test.dart
metrics/web/test/dashboard/presentation/widgets/build_result_bar_test.dart
metrics/web/test/dashboard/presentation/widgets/strategy/build_result_bar_padding_strategy_test.dart

feat: Redesign the dashboard popup.

---

metrics/web/test/common/presentation/colored_bar/theme/attention_level/metrics_colored_bar_attention_level_test.dart
metrics/web/test/common/presentation/colored_bar/theme/style/metrics_colored_bar_style_test.dart
metrics/web/test/common/presentation/colored_bar/theme/theme_data/metrics_colored_bar_theme_data_test.dart
metrics/web/test/common/presentation/graph_indicator/theme/attention_level/graph_indicator_attention_level_test.dart
metrics/web/test/common/presentation/graph_indicator/theme/style/graph_indicator_style_test.dart
metrics/web/test/common/presentation/graph_indicator/theme/theme_data/graph_indicator_theme_data_test.dart
metrics/web/test/common/presentation/metrics_theme/model/dark_metrics_theme_data_test.dart
metrics/web/test/common/presentation/metrics_theme/model/light_metrics_theme_data_test.dart
metrics/web/test/common/presentation/metrics_theme/model/metrics_theme_data_test.dart

test: Add tests to dashboard popup (theme).

---

metrics/web/lib/base/presentation/widgets/base_popup.dart
metrics/web/lib/base/presentation/widgets/circle_graph_indicator.dart
metrics/web/lib/common/presentation/colored_bar/widgets/metrics_colored_bar.dart
metrics/web/lib/dashboard/presentation/widgets/build_result_bar.dart
metrics/web/lib/dashboard/presentation/widgets/build_result_bar_graph.dart
metrics/web/lib/dashboard/presentation/widgets/strategy/build_result_bar_style_strategy.dart
metrics/web/test/base/presentation/graphs/bar_graph_test.dart
metrics/web/test/base/presentation/widgets/base_popup_test.dart
metrics/web/test/base/presentation/widgets/circle_graph_indicator_test.dart
metrics/web/test/common/presentation/colored_bar/widgets/metrics_colored_bar_test.dart
metrics/web/test/common/presentation/graph_indicator/widgets/graph_indicator_test.dart
metrics/web/test/common/presentation/graph_indicator/widgets/negative_graph_indicator_test.dart
metrics/web/test/common/presentation/graph_indicator/widgets/neutral_graph_indicator_test.dart
metrics/web/test/common/presentation/graph_indicator/widgets/positive_graph_indicator_test.dart
metrics/web/test/dashboard/presentation/state/project_metrics_notifier_test.dart
metrics/web/test/dashboard/presentation/view_models/build_result_popup_view_model_test.dart
metrics/web/test/dashboard/presentation/view_models/build_result_view_model_test.dart
metrics/web/test/dashboard/presentation/widgets/build_result_bar_graph_test.dart
metrics/web/test/dashboard/presentation/widgets/build_result_bar_test.dart
metrics/web/test/dashboard/presentation/widgets/build_result_popup_card_test.dart
metrics/web/test/dashboard/presentation/widgets/strategy/build_result_bar_style_strategy_test.dart

test: Add tests to dashboard popup (widgets).

---

metrics/web/test_driver/common/config/driver_tests_config.dart

fix: Update chromedriver version to match latest Google Chrome

---

metrics/web/lib/dashboard/domain/usecases/receive_project_metrics_updates.dart
metrics/web/lib/dashboard/presentation/state/project_metrics_notifier.dart
metrics/web/test/dashboard/presentation/state/project_metrics_notifier_test.dart

fix: Fix performance and builds metrics loading

---

.github/workflows/ci_integrations_actions.yml
analysis_options.yaml
metrics/ci_integrations/lib/client/github_actions/github_actions_client.dart
metrics/ci_integrations/lib/client/github_actions/models/page.dart
metrics/ci_integrations/lib/client/github_actions/models/workflow_run.dart
metrics/ci_integrations/lib/client/github_actions/models/workflow_run_artifact.dart
metrics/ci_integrations/lib/client/github_actions/models/workflow_run_duration.dart
metrics/ci_integrations/lib/client/jenkins/model/jenkins_build.dart
metrics/ci_integrations/lib/client/jenkins/model/jenkins_build_artifact.dart
metrics/ci_integrations/lib/client/jenkins/model/jenkins_building_job.dart
metrics/ci_integrations/lib/client/jenkins/model/jenkins_job.dart
metrics/ci_integrations/lib/client/jenkins/model/jenkins_multi_branch_job.dart
metrics/ci_integrations/lib/client/jenkins/model/jenkins_query_limits.dart
metrics/ci_integrations/lib/util/model/interaction_result.dart
metrics/ci_integrations/test/cli/logger/logger_test.dart
metrics/ci_integrations/test/source/jenkins/adapter/jenkins_source_client_adapter_test.dart

ci: Implement CI Integrations Actions

---

metrics/web/lib/base/presentation/graphs/circle_percentage.dart
metrics/web/test/base/presentation/graphs/circle_percentage_test.dart
metrics/web/test_driver/common/config/driver_tests_config.dart

fix: Fix circle percentage value text displaying

---

metrics/web/lib/dashboard/presentation/widgets/build_result_bar.dart
metrics/web/lib/dashboard/presentation/widgets/project_metrics_tile.dart
metrics/web/test/dashboard/presentation/widgets/build_result_bar_test.dart

fix: Fix the performance of the Dashboard page.

---

metrics/ci_integrations/docs/diagrams/ci_integrations_coverage_class_diagram.puml
metrics/coverage_converter/docs/diagrams/coverage_interfaces_diagram.puml

fix: Improve coverage converter diagrams

---

metrics/ci_integrations/docs/github_actions/01_github_actions_client.md
metrics/ci_integrations/docs/github_actions/diagrams/github_actions_client_class_diagram.puml

docs: Changes to the GitHub actions client design

---

metrics/web/pubspec.lock
metrics/web/pubspec.yaml
metrics/web/test_driver/cli/web_driver/chrome_driver.dart
metrics/web/test_driver/cli/web_driver/process/chrome_driver_process.dart
metrics/web/test_driver/cli/web_driver/web_driver.dart
metrics/web/test_driver/flutter_web_driver.dart

feat: Make driver tests script use installed web driver if any

---

metrics/deploy/lib/cli/firebase/firebase_command.dart
metrics/deploy/lib/cli/flutter/flutter_command.dart
metrics/deploy/lib/cli/gcloud/gcloud_command.dart
metrics/deploy/lib/cli/git/git_command.dart
metrics/deploy/lib/doctor/doctor_command.dart

feat: doctor command refactor

---

metrics/ci_integrations/docs/diagrams/ci_integrations_coverage_class_diagram.puml
metrics/coverage_converter/docs/01_coverage_converter_design.md
metrics/coverage_converter/docs/diagrams/coverage_class_diagram.puml
metrics/coverage_converter/docs/diagrams/coverage_conversion_activity.puml
metrics/coverage_converter/docs/diagrams/coverage_interfaces_diagram.puml
metrics/coverage_converter/docs/diagrams/coverage_sequence_diagram.puml

fix: Rename CoverageModel to CoverageData in the Coverage Converter design document and fix typos

---

metrics/web/lib/auth/presentation/pages/loading_page.dart
metrics/web/lib/auth/presentation/pages/login_page.dart
metrics/web/lib/common/presentation/widgets/platform_brightness_observer.dart
metrics/web/test/auth/presentation/pages/loading_page_test.dart
metrics/web/test/auth/presentation/pages/login_page_test.dart
metrics/web/test/common/presentation/widgets/platform_brightness_observer_test.dart
metrics/web/test/test_utils/binding_util.dart

fix: Fix user profile creation on opening the logged-in application

---

metrics/ci_integrations/lib/source/jenkins/adapter/jenkins_source_client_adapter.dart
metrics/ci_integrations/test/source/jenkins/adapter/jenkins_source_client_adapter_test.dart
metrics/core/lib/src/data/model/build_data.dart
metrics/core/lib/src/data/model/project_data.dart
metrics/core/lib/src/domain/entities/build.dart
metrics/core/lib/src/domain/entities/build_status.dart
metrics/core/lib/src/domain/entities/project.dart
metrics/core/test/data/model/build_data_test.dart
metrics/web/lib/dashboard/data/deserializer/build_data_deserializer.dart
metrics/web/lib/dashboard/domain/usecases/parameters/project_id_param.dart
metrics/web/lib/dashboard/presentation/widgets/build_result_bar.dart
metrics/web/lib/dashboard/presentation/widgets/project_build_status.dart
metrics/web/lib/dashboard/presentation/widgets/strategy/build_result_bar_appearance_strategy.dart
metrics/web/lib/dashboard/presentation/widgets/strategy/build_result_bar_style_strategy.dart
metrics/web/lib/dashboard/presentation/widgets/strategy/project_build_status_style_strategy.dart
metrics/web/test/dashboard/data/deserializer/build_data_deserializer_test.dart
metrics/web/test/dashboard/domain/entities/metrics/project_build_status_metric_test.dart
metrics/web/test/dashboard/domain/usecases/receive_build_metrics_updates_test.dart
metrics/web/test/dashboard/presentation/view_models/build_result_view_model_test.dart
metrics/web/test/dashboard/presentation/view_models/project_build_status_view_model_test.dart
metrics/web/test/dashboard/presentation/view_models/project_metrics_tile_view_model_test.dart
metrics/web/test/dashboard/presentation/widgets/build_result_bar_graph_test.dart
metrics/web/test/dashboard/presentation/widgets/build_result_bar_test.dart
metrics/web/test/dashboard/presentation/widgets/strategy/build_result_bar_appearance_strategy_test.dart
metrics/web/test/dashboard/presentation/widgets/strategy/build_result_bar_padding_strategy_test.dart
metrics/web/test/dashboard/presentation/widgets/strategy/build_result_bar_style_strategy_test.dart
metrics/web/test/dashboard/presentation/widgets/strategy/project_build_status_style_strategy_test.dart

feat: Change BuildStatus to include 3 states (success, failed, unknown)

---

metrics/ci_integrations/lib/source/github_actions/config/model/github_actions_source_config.dart
metrics/ci_integrations/test/source/github_actions/config/model/github_actions_source_config_test.dart
metrics/ci_integrations/test/source/github_actions/test_utils/test_data/github_actions_config_test_data.dart

fix: Change Github Actions config

---

docs/02_process.md

docs: Add design first and design documentation sections, move bash scripts

---

metrics/coverage_converter/docs/01_coverage_converter_design.md
metrics/coverage_converter/docs/diagrams/coverage_class_diagram.puml
metrics/coverage_converter/docs/diagrams/coverage_interfaces_diagram.puml
metrics/coverage_converter/docs/diagrams/coverage_sequence_diagram.puml

feat: Improve coverage arguments parsing design

---

metrics/coverage_converter/bin/main.dart
metrics/coverage_converter/lib/common/arguments/model/coverage_converter_arguments.dart
metrics/coverage_converter/lib/common/arguments/parser/arguments_parser.dart
metrics/coverage_converter/lib/common/arguments/parser/coverage_converter_arguments_parser.dart
metrics/coverage_converter/lib/common/runner/coverage_converter_runner.dart
metrics/coverage_converter/pubspec.yaml
metrics/coverage_converter/test/common/arguments/model/coverage_converter_arguments_test.dart
metrics/coverage_converter/test/common/arguments/parser/arguments_parser_test.dart
metrics/coverage_converter/test/common/arguments/parser/coverage_converter_arguments_parser_test.dart
metrics/coverage_converter/test/common/runner/coverage_converter_runner_test.dart

feat: Coverage converter arguments parser and runner

---

metrics/ci_integrations/docs/buildkite/01_buildkite_client.md
metrics/ci_integrations/docs/buildkite/diagrams/buildkite_client_class_diagram.puml

docs: Create Buildkite REST API Client Design document.

---

metrics/ci_integrations/lib/cli/parties/supported_source_parties.dart
metrics/ci_integrations/lib/source/github_actions/client_factory/github_actions_source_client_factory.dart
metrics/ci_integrations/lib/source/github_actions/party/github_actions_source_party.dart
metrics/ci_integrations/test/cli/parties/supported_source_parties_test.dart
metrics/ci_integrations/test/source/github_actions/client_factory/github_actions_source_client_factory_test.dart
metrics/ci_integrations/test/source/github_actions/party/github_actions_source_party_test.dart

feat: Integrate Github Actions Source Client to CLI

---

metrics/coverage_converter/lib/common/command/coverage_converter_command.dart
metrics/coverage_converter/lib/common/converter/coverage_converter.dart
metrics/coverage_converter/lib/common/exception/coverage_converter_exception.dart
metrics/coverage_converter/pubspec.yaml
metrics/coverage_converter/test/common/command/coverage_converter_command_test.dart
metrics/coverage_converter/test/common/exception/coverage_converter_exception_test.dart
metrics/coverage_converter/test/utils/file_mock.dart

feat: Coverage converter main abstract classes and interfaces

---

.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/task.md
.github/pull_request_template.md

chore: update github templates to improve process

---

.github/workflows/coverage_converter_actions.yml
.github/workflows/coverage_converter_publish_actions.yml

feat: Coverage Converter: setup macOS, linux publishing

---

metrics/ci_integrations/test/client/github_actions/test_utils/mock/github_actions_mock_server.dart

test: Implement GitHub Actions Mock Server

---

metrics/ci_integrations/lib/client/buildkite/mappers/buildkite_build_state_mapper.dart
metrics/ci_integrations/lib/client/buildkite/models/buildkite_build_state.dart
metrics/ci_integrations/test/client/buildkite/mappers/buildkite_build_state_mapper_test.dart

feat: Implement Buildkite client mappers.

---

metrics/ci_integrations/lib/client/github_actions/github_actions_client.dart
metrics/ci_integrations/test/client/github_actions/github_actions_client_test.dart

test: Add tests for the github actions client

---

metrics/coverage_converter/docs/01_coverage_converter_design.md
metrics/coverage_converter/docs/diagrams/converter_exception_class_diagram.puml
metrics/coverage_converter/docs/diagrams/coverage_class_diagram.puml
metrics/coverage_converter/docs/diagrams/coverage_conversion_activity.puml
metrics/coverage_converter/docs/diagrams/coverage_interfaces_diagram.puml
metrics/coverage_converter/docs/diagrams/coverage_sequence_diagram.puml

docs: CoverageConverter design improvement

---

metrics/core/lib/src/data/model/coverage_data.dart
metrics/core/lib/src/domain/entities/coverage.dart
metrics/core/test/data/model/coverage_data_test.dart
metrics/core/test/domain/entities/coverage_test.dart
metrics/coverage_converter/lib/common/command/coverage_converter_command.dart
metrics/coverage_converter/lib/common/converter/coverage_converter.dart
metrics/coverage_converter/lib/common/exception/coverage_converter_exception.dart
metrics/coverage_converter/lib/common/runner/coverage_converter_runner.dart
metrics/coverage_converter/lib/lcov/command/lcov_coverage_converter_command.dart
metrics/coverage_converter/lib/lcov/converter/lcov_coverage_converter.dart
metrics/coverage_converter/pubspec.yaml
metrics/coverage_converter/test/common/command/coverage_converter_command_test.dart
metrics/coverage_converter/test/common/exception/coverage_converter_exception_test.dart
metrics/coverage_converter/test/common/runner/coverage_converter_runner_test.dart
metrics/coverage_converter/test/lcov/command/lcov_coverage_converter_command_test.dart
metrics/coverage_converter/test/lcov/converter/lcov_coverge_converter_test.dart

feat: Implement LCOV coverage converter

---

.github/workflows/ci_integrations_actions.yml
.github/workflows/coverage_converter_actions.yml
.github/workflows/firebase_actions.yml
.github/workflows/metrics_actions.yml
.github/workflows/web_actions.yml

feat: Improve GitHub actions

---

metrics/ci_integrations/docs/buildkite/diagrams/buildkite_client_class_diagram.puml
metrics/ci_integrations/lib/client/buildkite/buildkite_client.dart
metrics/ci_integrations/lib/client/buildkite/constants/buildkite_constants.dart
metrics/ci_integrations/lib/client/buildkite/models/buildkite_artifact.dart
metrics/ci_integrations/lib/client/buildkite/models/buildkite_build.dart
metrics/ci_integrations/lib/client/github_actions/github_actions_client.dart
metrics/ci_integrations/test/client/buildkite/buildkite_client_test.dart
metrics/ci_integrations/test/client/buildkite/models/buildkite_artifact_test.dart
metrics/ci_integrations/test/client/buildkite/models/buildkite_artifacts_page_test.dart
metrics/ci_integrations/test/client/buildkite/models/buildkite_build_test.dart
metrics/ci_integrations/test/client/buildkite/models/buildkite_builds_page_test.dart

feat: Implement Buildkite client.

---

.github/workflows/ci_integrations_actions.yml
.github/workflows/coverage_converter_actions.yml
.github/workflows/web_actions.yml

fix: Fix GitHub Actions triggers

---

.github/workflows/ci_integrations_actions.yml
.github/workflows/coverage_converter_actions.yml
.github/workflows/web_actions.yml
metrics/ci_integrations/lib/source/github_actions/adapter/github_actions_source_adapter.dart
metrics/core/lib/src/data/model/coverage_data.dart
metrics/core/test/data/model/coverage_data_test.dart

fix: Fix GitHub coverage fetching and Coverage data model

---

metrics/coverage_converter/pubspec.yaml

fix: Add test coverage dependency to the coverage converter

---

metrics/ci_integrations/lib/client/github_actions/models/workflow_run.dart
metrics/ci_integrations/lib/client/github_actions/models/workflow_run_job.dart
metrics/ci_integrations/test/client/github_actions/models/workflow_run_job_test.dart
metrics/ci_integrations/test/client/github_actions/models/workflow_run_test.dart

fix: URLs in models must link to Github web

---

metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart

fix: Fix the UserMenuTheme and ToggleTheme.

---

metrics/ci_integrations/docs/01_ci_integration_module_architecture.md
metrics/ci_integrations/lib/client/buildkite/buildkite_client.dart
metrics/ci_integrations/lib/client/github_actions/github_actions_client.dart
metrics/ci_integrations/lib/source/buildkite/adapter/buildkite_source_client_adapter.dart

feat: Create adapter for Buildkite client.

---

metrics/ci_integrations/test/client/buildkite/test_utils/mock/buildkite_mock_server.dart
metrics/ci_integrations/test/client/github_actions/test_utils/mock/github_actions_mock_server.dart
metrics/ci_integrations/test/client/jenkins/test_utils/mock/jenkins_mock_server.dart
metrics/ci_integrations/test/client/test_utils/mock_server_utils.dart

test: Buildkite mock server

---

.metrics/ci_integrations_config.yml
.metrics/coverage_converter_config.yml
.metrics/metrics_web_config.yml
metrics/ci_integrations/config.yaml
metrics/ci_integrations/lib/destination/firestore/client_factory/firestore_destination_client_factory.dart
metrics/ci_integrations/lib/destination/firestore/config/model/firestore_destination_config.dart
metrics/ci_integrations/test/cli/test_util/test_data/config_test_data.dart
metrics/ci_integrations/test/destination/firestore/config/model/firestore_destination_config_test.dart
metrics/ci_integrations/test/destination/firestore/test_utils/test_data/firestore_config_test_data.dart

fix: Rename firebase API key to the firebase public API key.

---

metrics/ci_integrations/lib/cli/parties/supported_source_parties.dart
metrics/ci_integrations/lib/source/buildkite/client_factory/buildkite_source_client_factory.dart
metrics/ci_integrations/lib/source/buildkite/party/buildkite_source_party.dart
metrics/ci_integrations/test/cli/parties/supported_source_parties_test.dart
metrics/ci_integrations/test/source/buildkite/client_factory/buildkite_source_client_factory_test.dart
metrics/ci_integrations/test/source/buildkite/party/buildkite_source_party_test.dart

feat: Integrate Adapter/SourceClient to CI Integrations

---

metrics/ci_integrations/pubspec.yaml
metrics/coverage_converter/pubspec.yaml

fix: Fix test_coverage dependency to be compatible with latest coverage package

---

.github/workflows/metrics_integration_actions.yml

fix: Update Ci Integrations link to point to latest version

---

metrics/ci_integrations/test/source/buildkite/adapter/buildkite_source_client_adapter_test.dart
metrics/ci_integrations/test/source/buildkite/adapter/buildkite_source_client_adpter_test.dart
metrics/ci_integrations/test/source/buildkite/test_utils/test_data/buildkite_test_data_generator.dart
metrics/ci_integrations/test/source/github_actions/adapter/github_actions_source_client_adapter_test.dart
metrics/ci_integrations/test/test_utils/extensions/interaction_result_answer.dart

test: Create tests for Buildkite Adapter

---

metrics/ci_integrations/test/client/buildkite/buildkite_client_test.dart
metrics/ci_integrations/test/client/buildkite/test_utils/mock/buildkite_mock_server.dart

test: Buildkite client tests

---

.github/workflows/ci_integrations_actions.yml

feat: Configure CI Integrations publishing GitHub Actions

---

metrics/ci_integrations/pubspec.yaml
metrics/coverage_converter/pubspec.yaml

feat: Update `test_coverage` and `coverage` packages versions to latest

---

.github/workflows/metrics_integration_actions.yml

feat: Update CI Integrations links to point to GitHub releases

---

metrics/web/test_driver/cli/web_driver/chrome_driver.dart
metrics/web/test_driver/common/config/driver_tests_config.dart
metrics/web/test_driver/flutter_web_driver.dart

test: Update Driver Tests

---

metrics/ci_integrations/lib/source/github_actions/adapter/github_actions_source_adapter.dart
metrics/ci_integrations/test/source/github_actions/adapter/github_actions_source_client_adapter_test.dart

feat: Treat timeout as failed

---

docs/16_dependencies_licenses.md

docs: Create dependencies licenses document

---

metrics/web/test_driver/common/config/driver_tests_config.dart

fix: Update Chrome driver version

---

.github/workflows/web_actions.yml
docs/16_dependencies_licenses.md
metrics/web/lib/util/web_platform.dart
metrics/web/pubspec.lock
metrics/web/pubspec.yaml

feat: Skia deployment - enable auto renderer

---

metrics/ci_integrations/lib/source/buildkite/adapter/buildkite_source_client_adapter.dart
metrics/ci_integrations/lib/source/github_actions/adapter/github_actions_source_adapter.dart
metrics/ci_integrations/lib/source/jenkins/adapter/jenkins_source_client_adapter.dart
metrics/ci_integrations/test/source/buildkite/adapter/buildkite_source_client_adapter_test.dart
metrics/ci_integrations/test/source/github_actions/adapter/github_actions_source_client_adapter_test.dart
metrics/ci_integrations/test/source/jenkins/adapter/jenkins_source_client_adapter_test.dart

feat: [CI Integrations] Default values for BuildData

---

metrics/core/lib/src/domain/value_objects/email.dart

docs: Update Email value object documentation

---

.github/workflows/metrics_integration_actions.yml
.metrics/buildkite/integration_config.yml
.metrics/ci_integrations_config.yml
.metrics/coverage_converter_config.yml
.metrics/metrics_web_config.yml
docs/09_firebase_deployment.md

docs: Firebase key restrictions

---

metrics/web/docs/features/firebase_analytics/01_firebase_analytics_design.md

fix: Change the diagrams links to master

---

metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
metrics/web/lib/common/presentation/tooltip_icon/widgets/tooltip_icon.dart
metrics/web/lib/common/presentation/tooltip_popup/theme/theme_data/tooltip_popup_theme_data.dart
metrics/web/lib/common/presentation/tooltip_popup/widgets/tooltip_popup.dart
metrics/web/lib/common/presentation/widgets/tooltip_title.dart
metrics/web/lib/dashboard/presentation/strings/dashboard_strings.dart
metrics/web/lib/dashboard/presentation/widgets/metrics_table_row.dart
metrics/web/lib/dashboard/presentation/widgets/metrics_table_title_header.dart
metrics/web/lib/dashboard/presentation/widgets/project_metrics_tile.dart
metrics/web/test/common/presentation/tooltip_icon/widgets/tooltip_icon_test.dart
metrics/web/test/common/presentation/tooltip_popup/theme/theme_data/tooltip_popup_theme_data_test.dart
metrics/web/test/common/presentation/tooltip_popup/widgets/tooltip_popup_test.dart
metrics/web/test/common/presentation/widgets/tooltip_title_test.dart
metrics/web/test/dashboard/presentation/widgets/metrics_table_header_test.dart
metrics/web/test/dashboard/presentation/widgets/metrics_table_test.dart
metrics/web/test/dashboard/presentation/widgets/metrics_table_title_header_test.dart
metrics/web/web/icons/Info.svg

feat: Implement tooltip popup

---

metrics/ci_integrations/lib/cli/command/sync_command.dart
metrics/ci_integrations/lib/cli/error/sync_error.dart
metrics/ci_integrations/test/cli/command/sync_command_test.dart
metrics/ci_integrations/test/cli/error/sync_error_test.dart
metrics/ci_integrations/test/test_utils/matcher_util.dart

feat: Improve CI Integrations error handling

---

metrics/web/lib/base/presentation/graphs/bar_graph.dart
metrics/web/lib/base/presentation/graphs/circle_percentage.dart
metrics/web/lib/base/presentation/graphs/placeholder_bar.dart
metrics/web/lib/base/presentation/graphs/sparkline_graph.dart

feat: Improve base graphs documentation

---

.metrics/jenkins/metrics_web_config.yml

feat: Add Metrics Web Jenkins ci integrations config

---

metrics/web/lib/common/domain/entities/instant_config.dart
metrics/web/lib/common/domain/repositories/instant_config_repository.dart
metrics/web/lib/common/domain/usecases/fetch_instant_config_usecase.dart
metrics/web/lib/common/domain/usecases/parameters/instant_config_param.dart
metrics/web/test/common/domain/entities/instant_config_test.dart
metrics/web/test/common/domain/usecases/fetch_instant_config_usecase_test.dart
metrics/web/test/common/domain/usecases/parameters/instant_config_param_test.dart

feat: Implement domain layer for Instant Config feature

---

.metrics/jenkins/ci_integrations_config.yml
.metrics/jenkins/coverage_converter_config.yml

feat: Configure Coverage Converter and CI Integrations builds import from Jenkins

---

docs/16_dependencies_licenses.md
metrics/web/lib/analytics/data/repositories/firebase_analytics_repository.dart
metrics/web/lib/analytics/domain/repositories/analytics_repository.dart
metrics/web/lib/analytics/domain/usecases/log_login_use_case.dart
metrics/web/lib/analytics/domain/usecases/reset_user_use_case.dart
metrics/web/pubspec.yaml
metrics/web/test/analytics/domain/usecases/log_login_use_case_test.dart
metrics/web/test/analytics/domain/usecases/reset_user_use_case_test.dart
metrics/web/web/index.html

feat: Implement Firebase Analytics Data layer

---

metrics/web/lib/common/data/model/instant_config_data.dart
metrics/web/lib/common/data/repositories/firestore_instant_config_repository.dart
metrics/web/lib/common/domain/entities/instant_config.dart
metrics/web/test/common/data/model/instant_config_data_test.dart
metrics/web/test/common/domain/usecases/fetch_instant_config_usecase_test.dart

feat: Instant config data layer

---

metrics/firebase/firestore/rules/firestore.rules
metrics/firebase/test/firestore/rules/instant-config-test.js
metrics/firebase/test/firestore/rules/test_utils/test-data.js

feat: Instant Config Firestore rules

---

metrics/web/lib/analytics/domain/usecases/parameters/page_name_param.dart
metrics/web/lib/analytics/presentation/state/analytics_notifier.dart
metrics/web/lib/auth/presentation/pages/login_page.dart
metrics/web/lib/common/domain/usecases/parameters/user_id_param.dart
metrics/web/lib/common/presentation/injector/widget/injection_container.dart
metrics/web/lib/common/presentation/routes/observers/firebase_analytics_observer.dart
metrics/web/lib/common/presentation/widgets/metrics_user_menu.dart
metrics/web/lib/main.dart
metrics/web/test/analytics/presentation/state/analytics_notifier_test.dart
metrics/web/test/common/presentation/injector/widget/injection_container_test.dart
metrics/web/test/common/presentation/routes/observers/firebase_analytics_observer_test.dart
metrics/web/test/common/presentation/widgets/metrics_user_menu_test.dart
metrics/web/test/test_utils/analytics_notifier_mock.dart
metrics/web/test/test_utils/analytics_notifier_stub.dart
metrics/web/test/test_utils/auth_notifier_stub.dart
metrics/web/test/test_utils/signed_in_auth_notifier_stub.dart
metrics/web/test/test_utils/test_injection_container.dart

feat: Implement Firebase Analytics Presentation layer

---

metrics/web/lib/common/presentation/strings/common_strings.dart
metrics/web/lib/common/presentation/widgets/metrics_user_menu.dart
metrics/web/lib/instant_config/data/model/instant_config_data.dart
metrics/web/lib/instant_config/domain/entities/instant_config.dart
metrics/web/lib/instant_config/domain/usecases/fetch_instant_config_usecase.dart
metrics/web/lib/instant_config/domain/usecases/parameters/instant_config_param.dart
metrics/web/lib/instant_config/presentation/state/instant_config_notifier.dart
metrics/web/lib/instant_config/presentation/view_models/debug_menu_instant_config_view_model.dart
metrics/web/test/common/presentation/widgets/metrics_user_menu_test.dart
metrics/web/test/instant_config/data/model/instant_config_data_test.dart
metrics/web/test/instant_config/domain/entities/instant_config_test.dart
metrics/web/test/instant_config/domain/usecases/fetch_instant_config_usecase_test.dart
metrics/web/test/instant_config/domain/usecases/parameters/instant_config_param_test.dart
metrics/web/test/instant_config/presentation/state/instant_config_notifier_test.dart
metrics/web/test/instant_config/presentation/view_models/debug_menu_instant_config_view_model_test.dart
metrics/web/test/test_utils/instant_config_notifier_stub.dart

feat: Add Debug Menu to Instant Config, Add Debug Menu item to User Menu

---

metrics/firebase/firestore/rules/firestore.rules
metrics/firebase/test/firestore/rules/feature-config-test.js
metrics/firebase/test/firestore/rules/test_utils/test-data.js

feat: Create rules for Feature Config collection

---

.github/workflows/metrics_actions.yml

fix: Fix links checker to include renamed files

---

metrics/web/lib/common/presentation/metrics_theme/config/color_config.dart
metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
metrics/web/web/icons/unknown_status.svg

fix: Update light and dark tooltip colors

---

metrics/web/lib/common/presentation/injector/widget/injection_container.dart
metrics/web/test/common/presentation/injector/widget/injection_container_test.dart
metrics/web/test/test_utils/matcher_util.dart

fix: Fix notifiers disposing

---

metrics/web/lib/debug_menu/domain/entities/local_config.dart
metrics/web/lib/debug_menu/domain/repositories/local_config_repository.dart
metrics/web/lib/debug_menu/domain/usecases/close_local_config_storage_usecase.dart
metrics/web/lib/debug_menu/domain/usecases/open_local_config_storage_usecase.dart
metrics/web/lib/debug_menu/domain/usecases/parameters/local_config_param.dart
metrics/web/lib/debug_menu/domain/usecases/read_local_config_usecase.dart
metrics/web/lib/debug_menu/domain/usecases/update_local_config_usecase.dart
metrics/web/test/debug_menu/domain/entities/local_config_test.dart
metrics/web/test/debug_menu/domain/usecases/close_local_config_storage_usecase_test.dart
metrics/web/test/debug_menu/domain/usecases/open_local_config_storage_usecase_test.dart
metrics/web/test/debug_menu/domain/usecases/parameters/local_config_param_test.dart
metrics/web/test/debug_menu/domain/usecases/read_local_config_usecase_test.dart
metrics/web/test/debug_menu/domain/usecases/update_local_config_usecase_test.dart
metrics/web/test/test_utils/local_config_repository_mock.dart

feat: Implement Debug Menu Domain Layer

---

docs/16_dependencies_licenses.md
metrics/web/lib/common/domain/entities/persistent_store_error_code.dart
metrics/web/lib/common/presentation/models/persistent_store_error_message.dart
metrics/web/lib/common/presentation/strings/common_strings.dart
metrics/web/lib/debug_menu/data/model/local_config_data.dart
metrics/web/lib/debug_menu/data/repositories/hive_local_config_repository.dart
metrics/web/lib/debug_menu/domain/repositories/local_config_repository.dart
metrics/web/pubspec.yaml
metrics/web/test/common/presentation/models/persistent_store_error_message_test.dart
metrics/web/test/debug_menu/data/model/local_config_data_test.dart

feat: Implement Debug Menu Data Layer

---

metrics/web/docs/features/sentry/01_sentry_design.md
metrics/web/docs/features/sentry/diagrams/sentry_util_class_diagram.puml
metrics/web/docs/features/user_profile_theme/01_user_profile_theme_design.md

docs: create Sentry Design document

---

.github/workflows/metrics_integration_actions.yml

fix: Fix sending slack notifications in Metrics Integration Actions

---

.github/workflows/ci_integrations_actions.yml
.github/workflows/coverage_converter_actions.yml

feat: Update Github release actions to use Github CLI

---

metrics/web/lib/auth/presentation/widgets/password_sign_in_option.dart
metrics/web/pubspec.yaml
metrics/web/test_driver/integration_test.dart

test: Migrate driver tests

---

metrics/web/lib/common/presentation/injector/widget/injection_container.dart
metrics/web/lib/common/presentation/pages/loading_page.dart
metrics/web/lib/debug_menu/presentation/state/debug_menu_notifier.dart
metrics/web/lib/debug_menu/presentation/view_models/fps_monitor_local_config_view_model.dart
metrics/web/test/common/presentation/injector/widget/injection_container_test.dart
metrics/web/test/common/presentation/pages/loading_page_test.dart
metrics/web/test/debug_menu/presentation/state/debug_menu_notifier_test.dart
metrics/web/test/debug_menu/presentation/view_models/fps_monitor_local_config_view_model_test.dart
metrics/web/test/test_utils/debug_menu_notifier_mock.dart
metrics/web/test/test_utils/debug_menu_notifier_stub.dart
metrics/web/test/test_utils/test_injection_container.dart

feat: Implement Debug Menu Presentation Layer

---

metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
metrics/web/lib/common/presentation/metrics_theme/model/debug_menu/debug_menu_theme_data.dart
metrics/web/lib/common/presentation/metrics_theme/model/debug_menu/theme_data/debug_menu_theme_data.dart
metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
metrics/web/lib/common/presentation/metrics_theme/model/metrics_theme_data.dart
metrics/web/test/common/presentation/metrics_theme/model/dark_metrics_theme_data_test.dart
metrics/web/test/common/presentation/metrics_theme/model/debug_menu/debug_menu_theme_data_test.dart
metrics/web/test/common/presentation/metrics_theme/model/light_metrics_theme_data_test.dart
metrics/web/test/common/presentation/metrics_theme/model/metrics_theme_data_test.dart

feat: Implement Debug Menu Theme

---

metrics/web/lib/project_groups/presentation/widgets/add_project_group_card.dart
metrics/web/lib/project_groups/presentation/widgets/delete_project_group_dialog.dart
metrics/web/lib/project_groups/presentation/widgets/project_group_card.dart
metrics/web/lib/project_groups/presentation/widgets/project_group_dialog.dart
metrics/web/test/project_groups/presentation/widgets/delete_project_group_dialog_test.dart
metrics/web/test/project_groups/presentation/widgets/project_group_card_test.dart
metrics/web/test/project_groups/presentation/widgets/project_group_dialog_test.dart

fix: Fix resetting project group dialog view models

---

docs/16_dependencies_licenses.md

docs: Add uuid dependency to the dependencies document

---

metrics/web/docs/features/navigation/diagrams/navigation_class_diagram.puml
metrics/web/lib/common/presentation/navigation/metrics_page/metrics_page.dart
metrics/web/lib/common/presentation/navigation/metrics_page/metrics_page_factory.dart
metrics/web/lib/common/presentation/navigation/metrics_page/metrics_page_route.dart
metrics/web/lib/common/presentation/routes/route_generator.dart
metrics/web/pubspec.yaml
metrics/web/test/common/presentation/navigation/metrics_page/metrics_page_factory_test.dart
metrics/web/test/common/presentation/navigation/metrics_page/metrics_page_route_test.dart
metrics/web/test/common/presentation/navigation/metrics_page/metrics_page_test.dart
metrics/web/test/common/presentation/routes/route_generator_test.dart
metrics/web/test/test_utils/matcher_util.dart

feat: Implement MetricsPage and MetricsPageFactory

---

.github/workflows/web_actions.yml

build: Add Sentry autoreleases

---

metrics/web/test/project_groups/presentation/widgets/project_group_dialog_test.dart

test: Improve project group dialog tests

---

metrics/web/docs/features/navigation/01_navigation_design.md
metrics/web/docs/features/navigation/diagrams/internal_navigation_sequence_diagram.puml
metrics/web/docs/features/navigation/diagrams/navigation_class_diagram.puml
metrics/web/docs/features/navigation/diagrams/not_initialized_app_navigation_sequence_diagram.puml

docs: Update Navigator2.0 design

---

metrics/web/lib/common/presentation/injector/widget/injection_container.dart
metrics/web/lib/common/presentation/navigation/constants/metrics_routes.dart
metrics/web/lib/common/presentation/navigation/state/navigation_notifier.dart
metrics/web/test/common/presentation/injector/widget/injection_container_test.dart
metrics/web/test/common/presentation/navigation/state/navigation_notifier_test.dart
metrics/web/test/common/presentation/navigation/state/navigator_notifier_test.dart

feat: Implement Navigation Notifier

---

docs/18_github_actions_metrics_integration.md

credits for spotting: @solid-vladlaba

docs: fix typo in "properties"

---

metrics/web/lib/common/presentation/navigation/metrics_route_information_parser.dart
metrics/web/lib/common/presentation/navigation/metrics_router_delegate.dart
metrics/web/lib/common/presentation/navigation/route_configuration/route_configuration_factory.dart
metrics/web/test/common/presentation/navigation/metrics_page/metrics_page_factory_test.dart
metrics/web/test/common/presentation/navigation/metrics_route_information_parser_test.dart
metrics/web/test/common/presentation/navigation/metrics_router_delegate_test.dart
metrics/web/test/common/presentation/navigation/route_configuration/route_configuration_factory_test.dart
metrics/web/test/test_utils/route_configuration_stub.dart

feat: Implement Router

---

metrics/web/docs/features/metrics_logger/01_metrics_logger_design.md
metrics/web/docs/features/metrics_logger/diagrams/metrics_logger_class_diagram.puml
metrics/web/docs/features/metrics_logger/diagrams/metrics_logger_initialize_sequence_diagram.puml
metrics/web/docs/features/metrics_logger/diagrams/metrics_logger_log_error_sequence_diagram.puml
metrics/web/docs/features/metrics_logger/diagrams/metrics_logger_sentry_class_diagram.puml

Additional: update class diagrams with packages, fix typos, improve diagrams.

docs: Update Metrics Logger design

---

metrics/web/lib/metrics_logger/sentry/event_processors/sentry_event_processor.dart
metrics/web/lib/metrics_logger/sentry/event_processors/user_agent_event_processor.dart
metrics/web/lib/metrics_logger/sentry/writers/sentry_writer.dart
metrics/web/test/metrics_logger/sentry/event_processors/user_agent_event_processor_test.dart
metrics/web/test/metrics_logger/sentry/writers/sentry_writer_test.dart

feat: Pass user agent using EventProcessor

---

metrics/web/lib/debug_menu/presentation/pages/debug_menu_page.dart
metrics/web/lib/debug_menu/strings/debug_menu_strings.dart
metrics/web/lib/main.dart
metrics/web/lib/metrics_logger/writers/console_writer.dart
metrics/web/test/debug_menu/presentation/pages/debug_menu_page_test.dart
metrics/web/test/metrics_logger/writers/console_writer_test.dart

feat: Integrate Metrics Logger

---

docs/09_firebase_deployment.md

docs: Update Build/Deployment Instructions

---

metrics/web/docs/features/metrics_logger/01_metrics_logger_design.md

fix: Fix typo in Metrics Logger design document

---

docs/09_firebase_deployment.md
docs/14_firebase_deployment_cli.md
metrics/web/README.md

docs: Update documentation to not use `flutter version`

---

docs/09_firebase_deployment.md
docs/14_firebase_deployment_cli.md
metrics/web/__/firebase/init.js
metrics/web/web/index.html

feat: Firebase auto config

---

.github/workflows/ci_integrations_actions.yml
.github/workflows/coverage_converter_actions.yml
.github/workflows/metrics_actions.yml
.github/workflows/web_actions.yml
docs/09_firebase_deployment.md
docs/14_firebase_deployment_cli.md
docs/15_developer_configuration.md
metrics/web/README.md
metrics/web/test_driver/cli/common/process/process_wrapper.dart
metrics/web/test_driver/cli/flutter/runner/flutter_drive_process_runner.dart
metrics/web/test_driver/process_manager/process_manager.dart

build: Update Flutter version, fix driver tests

---

.github/workflows/web_actions.yml
docs/09_firebase_deployment.md
docs/16_dependencies_licenses.md
metrics/web/lib/auth/data/repositories/firebase_user_repository.dart
metrics/web/lib/common/domain/entities/metrics_config.dart
metrics/web/lib/common/presentation/injector/widget/injection_container.dart
metrics/web/lib/common/presentation/metrics_app/metrics_app.dart
metrics/web/lib/main.dart
metrics/web/lib/metrics_logger/sentry/writers/sentry_writer.dart
metrics/web/lib/platform/stub/metrics_config/metrics_config_factory.dart
metrics/web/lib/platform/web/metrics_config/metrics_config_factory.dart
metrics/web/lib/platform/web/metrics_config/web_metrics_config.dart
metrics/web/pubspec.yaml
metrics/web/test/common/presentation/injector/widget/injection_container_test.dart
metrics/web/test/metrics_logger/sentry/writers/sentry_writer_test.dart
metrics/web/test/test_utils/metrics_config_mock.dart
metrics/web/test/test_utils/metrics_config_stub.dart
metrics/web/test_driver/app_test.dart
metrics/web/web/index.html
metrics/web/web/metrics_config.js

feat: Introduce Metrics Config

---

.github/workflows/web_actions.yml

fix: Environment Variable substitution in actions

---

metrics/core/pubspec.yaml

fix: Lint sort_pub_dependencies

---

metrics/ci_integrations/docs/03_ci_integration_verbose_mode.md
metrics/ci_integrations/docs/diagrams/ci_integrations_verbose_mode_diagram.puml

docs: CI Integrations verbose mode design

---

metrics/web/docs/features/searchable_dropdown/01_searchable_dropdown_design.md
metrics/web/docs/features/searchable_dropdown/diagrams/project_groups_searchable_dropdown_widget_class_diagram.puml
metrics/web/docs/features/searchable_dropdown/diagrams/searchable_dropdown_widget_class_diagram.puml

docs: Searchable Dropdown design document

---

docs/09_firebase_deployment.md
docs/19_security_audit_document.md

docs: Security Audit document

---

.github/workflows/web_actions.yml
metrics/web/.firebaserc
metrics/web/firebase.json

build: Simplify Firebase hosting targets

---

.github/workflows/web_actions.yml

fix: Fix Production deploy command

---

metrics/ci_integrations/test/cli/logger/logger_test.dart

fix: Remove Logger tests

---

docs/16_dependencies_licenses.md
metrics/web/lib/base/presentation/widgets/scorecard.dart
metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
metrics/web/pubspec.yaml
metrics/web/test/base/presentation/widgets/scorecard_test.dart
metrics/web/test/dashboard/presentation/widgets/build_number_scorecard_test.dart

fix: Large builds per week numbers

---

docs/09_firebase_deployment.md
docs/14_firebase_deployment_cli.md

docs: Update deployment documents with `target` instructions

---

metrics/web/lib/dashboard/presentation/strings/dashboard_strings.dart

feat: Improve coverage metric description

---

metrics/ci_integrations/docs/04_ci_integrations_config_validator.md
metrics/ci_integrations/docs/diagrams/ci_integrations_config_validator_class_diagram.puml
metrics/ci_integrations/docs/diagrams/ci_integrations_config_validator_sequence_diagram.puml

docs: CI Integrations Config Validator design document

---

metrics/ci_integrations/docs/01_ci_integration_module_architecture.md
metrics/ci_integrations/docs/02_ci_integration_user_guide.md
metrics/ci_integrations/docs/diagrams/ci_integrations_class_diagram.puml

docs: CI Integrations: design additional parameter to skip-coverage

---

metrics/ci_integrations/lib/cli/command/sync_command.dart
metrics/ci_integrations/lib/cli/runner/ci_integration_runner.dart
metrics/ci_integrations/lib/integration/ci/ci_integration.dart
metrics/ci_integrations/lib/integration/ci/config/model/sync_config.dart
metrics/ci_integrations/lib/integration/interface/source/client/source_client.dart
metrics/ci_integrations/lib/source/buildkite/adapter/buildkite_source_client_adapter.dart
metrics/ci_integrations/lib/source/github_actions/adapter/github_actions_source_adapter.dart
metrics/ci_integrations/lib/source/jenkins/adapter/jenkins_source_client_adapter.dart
metrics/ci_integrations/test/cli/command/sync_command_test.dart
metrics/ci_integrations/test/cli/test_util/test_data/config_test_data.dart
metrics/ci_integrations/test/integration/ci/ci_integration_test.dart
metrics/ci_integrations/test/integration/ci/config/model/sync_config_test.dart
metrics/ci_integrations/test/integration/ci/test_utils/stub/source_client_stub.dart
metrics/core/lib/src/data/model/build_data.dart
metrics/core/lib/src/domain/entities/build.dart
metrics/core/test/data/model/build_data_test.dart

feat: Add `skip-coverage` flag to sync command

---

metrics/firebase/firestore/rules/firestore.rules
metrics/firebase/test/firestore/rules/builds-test.js
metrics/firebase/test/firestore/rules/test_utils/test-data.js

fix: Update Firestore Security rules

---

.github/workflows/metrics_actions.yml
metrics/ci_integrations/lib/cli/command/sync_command.dart
metrics/ci_integrations/lib/client/buildkite/models/buildkite_build.dart
metrics/ci_integrations/lib/integration/ci/ci_integration.dart
metrics/ci_integrations/lib/source/buildkite/adapter/buildkite_source_client_adapter.dart
metrics/ci_integrations/test/client/buildkite/models/buildkite_build_test.dart
metrics/ci_integrations/test/source/buildkite/adapter/buildkite_source_client_adapter_test.dart
metrics/ci_integrations/test/source/buildkite/test_utils/test_data/buildkite_test_data_generator.dart

feat: Buildkite fetch coverage

---

metrics/web/pubspec.yaml

fix: Builds on latest Flutter master

---

.buildkite/pipelines/prod_sync_pipeline.yml
.metrics/buildkite/prod_integration_config.yml

feat: Add production sync pipeline

---

.metrics/buildkite/prod_integration_config.yml

fix: Change names of Environment Variables

---

docs/09_firebase_deployment.md
docs/19_security_audit_document.md
metrics/web/web/index.html

build: Upgrade Firebase SDK version

---

docs/05_project_metrics.md
docs/06_metrics_dashboard.md
metrics/web/lib/dashboard/domain/usecases/receive_project_metrics_updates.dart
metrics/web/lib/dashboard/presentation/strings/dashboard_strings.dart
metrics/web/test/dashboard/domain/usecases/receive_build_metrics_updates_test.dart

feat: Change Stability metrics calculation

---

metrics/ci_integrations/docs/04_ci_integrations_config_validator.md
metrics/ci_integrations/docs/diagrams/ci_integrations_config_validator_class_diagram.puml
metrics/ci_integrations/docs/diagrams/ci_integrations_config_validator_sequence_diagram.puml

docs: Update Ci integrations config validator doc with `validate` command

---

docs/05_project_metrics.md
docs/06_metrics_dashboard.md
metrics/web/lib/common/presentation/metrics_theme/config/dimensions_config.dart
metrics/web/lib/dashboard/domain/usecases/receive_project_metrics_updates.dart
metrics/web/lib/dashboard/presentation/strings/dashboard_strings.dart
metrics/web/lib/dashboard/presentation/widgets/metrics_table_row.dart
metrics/web/lib/dashboard/presentation/widgets/strategy/build_result_bar_padding_strategy.dart
metrics/web/test/dashboard/domain/usecases/receive_build_metrics_updates_test.dart
metrics/web/test/dashboard/presentation/widgets/strategy/build_result_bar_padding_strategy_test.dart

feat: Build Result metric changes

---

metrics/web/lib/dashboard/presentation/widgets/build_result_bar.dart
metrics/web/test/dashboard/presentation/widgets/build_result_bar_test.dart

fix: Improve BuildResultBar hitTestBehaviour

---

metrics/web/lib/common/presentation/constants/duration_constants.dart
metrics/web/lib/dashboard/presentation/widgets/project_groups_dropdown_body.dart
metrics/web/test/dashboard/presentation/widgets/project_groups_dropdown_body_test.dart

feat: Project groups dropdown animation

---

metrics/ci_integrations/lib/client/buildkite/buildkite_client.dart
metrics/ci_integrations/test/client/buildkite/buildkite_client_test.dart
metrics/ci_integrations/test/client/buildkite/test_utils/mock/buildkite_mock_server.dart

feat: Extend Buildkite client to include validation-required methods

---

metrics/ci_integrations/lib/client/github_actions/github_actions_client.dart
metrics/ci_integrations/lib/client/github_actions/models/workflow_run.dart
metrics/ci_integrations/lib/source/github_actions/adapter/github_actions_source_client_adapter.dart
metrics/ci_integrations/test/client/github_actions/github_actions_client_test.dart
metrics/ci_integrations/test/client/github_actions/models/workflow_run_test.dart
metrics/ci_integrations/test/client/github_actions/test_utils/mock/github_actions_mock_server.dart
metrics/ci_integrations/test/source/buildkite/adapter/buildkite_source_client_adapter_test.dart
metrics/ci_integrations/test/source/github_actions/adapter/github_actions_source_client_adapter_test.dart

feat: GitHub Actions fetch coverage

---

metrics/ci_integrations/docs/source/github_actions/config/configuration_template.yaml

fix: Add missing fields to the Github Actions config template

---

metrics/docs/01_storing_database_metadata.md

docs: Store database metadata

---

.github/workflows/ci_integrations_actions.yml
.github/workflows/coverage_converter_actions.yml

feat: Publish sha for linux binaries

---

metrics/ci_integrations/lib/destination/error/destination_error.dart
metrics/ci_integrations/lib/destination/firestore/adapter/firestore_destination_client_adapter.dart
metrics/ci_integrations/test/destination/error/destination_error_test.dart
metrics/ci_integrations/test/destination/firestore/adapter/firestore_destination_client_adapter_test.dart

feat: CI integrations sync - check project exists

---

metrics/web/lib/common/presentation/metrics_theme/config/dimensions_config.dart
metrics/web/lib/dashboard/presentation/widgets/build_result_bar_graph.dart
metrics/web/lib/dashboard/presentation/widgets/metrics_table_row.dart
metrics/web/lib/dashboard/presentation/widgets/strategy/build_result_bar_padding_strategy.dart
metrics/web/test/dashboard/presentation/widgets/metrics_table_row_test.dart
metrics/web/test/dashboard/presentation/widgets/strategy/build_result_bar_padding_strategy_test.dart

feat: Implement a new bar chart design

---

metrics/cli/docs/01_metrics_cli_design.md
metrics/cli/docs/diagrams/deploy_command_activity_diagram.puml
metrics/cli/docs/diagrams/doctor_command_activity_diagram.puml
metrics/cli/docs/diagrams/metrics_cli_runner_class_diagram.puml
metrics/cli/docs/diagrams/services_class_diagram.puml

refactor: Metrics CLI doc: Improve naming. Fix non-ascii symbols

---

metrics/docs/02_analyze_sign_tools_for_macos.md
metrics/docs/02_sign_and_notarize_metrics_binaries.md

docs: Analyze sign tools for Metrics binaries

---

.github/workflows/cla.yml

Fixes #1104 
](https://github.com/platform-platform/monorepo/blob/cla_signatures/cla.md)

feat: Enable contributor CLA

---

metrics/ci_integrations/lib/integration/validation/model/field_validation_result.dart
metrics/ci_integrations/lib/integration/validation/model/validation_result_builder.dart
metrics/ci_integrations/lib/source/buildkite/config/model/buildkite_source_config_field.dart
metrics/ci_integrations/lib/source/buildkite/config/vaildator_factory/buildkite_source_validator_factory.dart
metrics/ci_integrations/lib/source/buildkite/config/validator/buildkite_source_validator.dart
metrics/ci_integrations/lib/source/buildkite/strings/buildkite_strings.dart
metrics/ci_integrations/test/integration/validation/model/field_validation_result_test.dart
metrics/ci_integrations/test/integration/validation/model/validation_result_builder_test.dart
metrics/ci_integrations/test/integration/validation/model/validation_result_test.dart
metrics/ci_integrations/test/source/buildkite/config/model/buildkite_source_config_field_test.dart
metrics/ci_integrations/test/source/buildkite/config/validator/buildkite_source_validator_test.dart
metrics/ci_integrations/test/source/buildkite/config/validator_factory/buildkite_source_validator_factory_test.dart
metrics/ci_integrations/test/test_utils/matcher_util.dart

feat: Implement BuildkiteSourceValidator, BuildkiteSourceValidatorFactory

---

metrics/web/lib/common/presentation/metrics_theme/config/dimensions_config.dart
metrics/web/lib/dashboard/presentation/widgets/build_result_bar.dart
metrics/web/lib/dashboard/presentation/widgets/build_result_bar_graph.dart
metrics/web/lib/dashboard/presentation/widgets/metrics_table_row.dart
metrics/web/lib/dashboard/presentation/widgets/project_metrics_tile.dart
metrics/web/lib/dashboard/presentation/widgets/strategy/build_result_bar_padding_strategy.dart
metrics/web/test/dashboard/presentation/widgets/strategy/build_result_bar_padding_strategy_test.dart

feat: Implement a bar chart to match latest design

---

metrics/cli/docs/03_enablig_firebase_authentication.md

docs: Investigate the way of enabling the Firebase Authentication

---

metrics/ci_integrations/lib/client/buildkite/buildkite_client.dart
metrics/ci_integrations/lib/client/github_actions/github_actions_client.dart
metrics/ci_integrations/lib/client/jenkins/jenkins_client.dart
metrics/ci_integrations/lib/constants/http_constants.dart
metrics/ci_integrations/lib/source/buildkite/client_factory/buildkite_source_client_factory.dart
metrics/ci_integrations/lib/source/buildkite/config/vaildator_factory/buildkite_source_validator_factory.dart
metrics/ci_integrations/lib/source/github_actions/client_factory/github_actions_source_client_factory.dart
metrics/ci_integrations/lib/source/jenkins/client_factory/jenkins_source_client_factory.dart
metrics/ci_integrations/test/client/buildkite/buildkite_client_test.dart
metrics/ci_integrations/test/client/github_actions/github_actions_client_test.dart
metrics/ci_integrations/test/client/jenkins/jenkins_client_test.dart

feat: Add an empty user-agent header for the API calls

---

metrics/cli/docs/04_managing_firestore_data.md
metrics/cli/docs/diagrams/services_class_diagram.puml

docs: Investigate the way of managing Firestore data

---

metrics/ci_integrations/lib/client/jenkins/model/jenkins_instance_info.dart
metrics/ci_integrations/lib/client/jenkins/model/jenkins_user.dart
metrics/ci_integrations/test/client/jenkins/model/jenkins_instance_info_test.dart
metrics/ci_integrations/test/client/jenkins/model/jenkins_user_test.dart

feat: Implement Jenkins models

---

metrics/cli/docs/02_enabling_firebase_analytics.md
metrics/cli/docs/03_enablig_firebase_authentication.md
metrics/cli/docs/04_managing_firestore_data.md
metrics/docs/02_sign_and_notarize_metrics_binaries.md

docs: Rename Analyze section to Analysis

---

docs/20_feature_design_template.md

chore: feature design template

---

docs/00_template.md

fix: Add missing closing punctuation to the template document.

---

metrics/ci_integrations/lib/client/github_actions/github_actions_client.dart
metrics/ci_integrations/lib/client/github_actions/models/github_token.dart
metrics/ci_integrations/test/client/github_actions/github_actions_client_test.dart
metrics/ci_integrations/test/client/github_actions/models/github_token_test.dart
metrics/ci_integrations/test/client/github_actions/test_utils/mock/github_actions_mock_server.dart

feat: Extend Github Actions client to include validation-required methods

---

metrics/web/docs/04_animation_library_approaches.md
metrics/web/docs/analysis/01_animation_library_approaches.md

docs: Animation handoff investigation document

---

metrics/ci_integrations/lib/integration/validation/printer/validation_result_printer.dart
metrics/ci_integrations/test/cli/logger/writer/io_logger_writer_test.dart
metrics/ci_integrations/test/integration/validation/printer/validation_result_printer_test.dart
metrics/ci_integrations/test/test_utils/mock/io_sink_mock.dart

feat: Implement ValidationResultPrinter

---

metrics/ci_integrations/lib/client/jenkins/jenkins_client.dart
metrics/ci_integrations/lib/client/jenkins/model/jenkins_user.dart
metrics/ci_integrations/test/client/buildkite/test_utils/mock/buildkite_mock_server.dart
metrics/ci_integrations/test/client/github_actions/test_utils/mock/github_actions_mock_server.dart
metrics/ci_integrations/test/client/jenkins/jenkins_client_test.dart
metrics/ci_integrations/test/client/jenkins/model/jenkins_user_test.dart
metrics/ci_integrations/test/client/jenkins/test_utils/mock/jenkins_mock_server.dart
metrics/ci_integrations/test/client/test_utils/mock_server_utils.dart

feat: Extend Jenkins client to include validation-required methods

---

metrics/cli/lib/prompt/prompter.dart
metrics/cli/lib/prompt/writer/prompt_writer.dart
metrics/cli/pubspec.yaml
metrics/cli/test/prompt/prompter_test.dart

feat: Implement Prompter.

---

metrics/cli/lib/interfaces/cli/cli.dart
metrics/cli/lib/interfaces/service/info_service.dart

feat: Implement base interfaces

---

metrics/ci_integrations/lib/client/jenkins/jenkins_client.dart
metrics/ci_integrations/lib/source/jenkins/config/validation_delegate/jenkins_source_validation_delegate.dart
metrics/ci_integrations/lib/source/jenkins/strings/jenkins_strings.dart
metrics/ci_integrations/test/source/jenkins/adapter/jenkins_source_client_adapter_test.dart
metrics/ci_integrations/test/source/jenkins/config/validation_delegate/jenkins_source_validation_delegate_test.dart
metrics/ci_integrations/test/source/jenkins/test_utils/jenkins_client_mock.dart

feat: Implement Jenkins Source Validation Delegate

---

metrics/cli/docs/01_metrics_cli_design.md
metrics/cli/docs/diagrams/prompt_class_diagram.puml
metrics/cli/lib/prompt/prompter.dart
metrics/cli/lib/prompt/writer/io_prompt_writer.dart
metrics/cli/lib/prompt/writer/prompt_writer.dart
metrics/cli/test/prompt/prompter_test.dart
metrics/cli/test/prompt/writer/io_prompt_writer_test.dart

feat: Implement IOPromptWriter

---

metrics/ci_integrations/lib/client/github_actions/github_actions_client.dart
metrics/ci_integrations/lib/source/github_actions/client_factory/github_actions_source_client_factory.dart
metrics/ci_integrations/lib/source/github_actions/config/model/github_actions_source_config_field.dart
metrics/ci_integrations/lib/source/github_actions/config/validator/github_actions_source_validator.dart
metrics/ci_integrations/lib/source/github_actions/config/validator_factory/github_actions_source_validator_factory.dart
metrics/ci_integrations/lib/source/github_actions/party/github_actions_source_party.dart
metrics/ci_integrations/lib/source/github_actions/strings/github_actions_strings.dart
metrics/ci_integrations/test/client/github_actions/github_actions_client_test.dart
metrics/ci_integrations/test/source/github_actions/config/model/github_actions_source_config_field_test.dart
metrics/ci_integrations/test/source/github_actions/config/validator/github_actions_source_validator_test.dart
metrics/ci_integrations/test/source/github_actions/config/validator_factory/github_actions_source_validator_factory_test.dart
metrics/ci_integrations/test/source/github_actions/party/github_actions_source_party_test.dart

feat: Implement GithubActionsSourceConfigValidator, GithubActionsSourceConfigValidatorFactory

---

metrics/ci_integrations/docs/04_ci_integrations_config_validator.md
metrics/ci_integrations/docs/diagrams/config_validator_base_class_diagram.puml
metrics/ci_integrations/docs/diagrams/config_validator_destination_class_diagram.puml
metrics/ci_integrations/docs/diagrams/config_validator_sequence_diagram.puml

docs: Update Config Validator with new validation result

---

metrics/cli/docs/diagrams/cli_interfaces_class_diagram.puml
metrics/cli/docs/diagrams/services_class_diagram.puml
metrics/cli/lib/flutter/cli/flutter_cli.dart
metrics/cli/lib/interfaces/cli/cli.dart

feat: Implement FlutterCLI

---

metrics/ci_integrations/lib/source/github_actions/config/validator/github_actions_source_validator.dart
metrics/ci_integrations/lib/source/github_actions/strings/github_actions_strings.dart
metrics/ci_integrations/test/source/github_actions/config/validator/github_actions_source_validator_test.dart

feat: Implement GithubActionsSourceConfigValidator

---

metrics/ci_integrations/lib/integration/validation/model/field_validation_result.dart
metrics/ci_integrations/lib/source/buildkite/config/validation_delegate/buildkite_source_validation_delegate.dart
metrics/ci_integrations/lib/source/buildkite/config/validator/buildkite_source_validator.dart
metrics/ci_integrations/lib/source/github_actions/config/validator/github_actions_source_validator.dart
metrics/ci_integrations/test/integration/validation/model/field_validation_result_test.dart
metrics/ci_integrations/test/integration/validation/printer/validation_result_printer_test.dart
metrics/ci_integrations/test/source/buildkite/config/validation_delegate/buildkite_source_validation_delegate_test.dart
metrics/ci_integrations/test/source/buildkite/config/validator/buildkite_source_validator_test.dart
metrics/ci_integrations/test/source/github_actions/config/validator/github_actions_source_validator_test.dart

feat: Update BuildkiteSourceValidationDelegate to match the latest designs

---

docs/16_dependencies_licenses.md
metrics/cli/docs/diagrams/services_class_diagram.puml
metrics/cli/lib/flutter/cli/flutter_cli.dart
metrics/cli/lib/git/cli/git_cli.dart

feat: Implement GitCli

---

metrics/cli/lib/npm/cli/npm_cli.dart

feat: Implement NpmCli

---

metrics/ci_integrations/lib/source/jenkins/config/validation_delegate/jenkins_source_validation_delegate.dart
metrics/ci_integrations/test/source/jenkins/config/validation_delegate/jenkins_source_validation_delegate_test.dart

feat: Update JenkinsSourceValidationDelegate to match the latest designs

---

metrics/ci_integrations/lib/client/buildkite/buildkite_client.dart
metrics/ci_integrations/lib/client/jenkins/jenkins_client.dart
metrics/ci_integrations/lib/source/buildkite/client_factory/buildkite_source_client_factory.dart
metrics/ci_integrations/lib/source/buildkite/config/validator_factory/buildkite_source_validator_factory.dart
metrics/ci_integrations/lib/source/jenkins/client_factory/jenkins_source_client_factory.dart
metrics/ci_integrations/lib/source/jenkins/config/model/jenkins_source_config_field.dart
metrics/ci_integrations/lib/source/jenkins/config/validator/jenkins_source_validator.dart
metrics/ci_integrations/lib/source/jenkins/config/validator_factory/jenkins_source_validator_factory.dart
metrics/ci_integrations/lib/source/jenkins/party/jenkins_source_party.dart
metrics/ci_integrations/lib/source/jenkins/strings/jenkins_strings.dart
metrics/ci_integrations/test/client/buildkite/buildkite_client_test.dart
metrics/ci_integrations/test/client/github_actions/github_actions_client_test.dart
metrics/ci_integrations/test/client/jenkins/jenkins_client_test.dart
metrics/ci_integrations/test/source/buildkite/config/validator/buildkite_source_validator_test.dart
metrics/ci_integrations/test/source/github_actions/config/validator/github_actions_source_validator_test.dart
metrics/ci_integrations/test/source/jenkins/config/model/jenkins_source_config_field_test.dart
metrics/ci_integrations/test/source/jenkins/config/validator/jenkins_source_validator_test.dart
metrics/ci_integrations/test/source/jenkins/config/validator_factory/jenkins_source_validator_factory_test.dart
metrics/ci_integrations/test/source/jenkins/party/jenkins_source_party_test.dart
metrics/ci_integrations/test/test_utils/mock/validation_result_builder_mock.dart

feat: Implement Jenkins SourceValidator and SourceValidatorFactory

---

metrics/ci_integrations/lib/source/github_actions/config/validation_delegate/github_actions_source_validation_delegate.dart
metrics/ci_integrations/lib/source/github_actions/config/validator/github_actions_source_validator.dart
metrics/ci_integrations/test/source/github_actions/config/validation_delegate/github_actions_source_validation_delegate_test.dart
metrics/ci_integrations/test/source/github_actions/config/validator/github_actions_source_validator_test.dart

feat: Update GithubActionsSourceValidationDelegate to match the latest designs

---

metrics/ci_integrations/docs/02_ci_integration_user_guide.md

docs: Update CI Integrations User Guide with the `validate` command

---

metrics/cli/lib/deploy/deploy_command.dart
metrics/cli/test/deploy/deploy_command_test.dart

fix: Fix analyzer warnings

---

metrics/ci_integrations/lib/destination/firestore/config/model/firestore_destination_config_field.dart
metrics/ci_integrations/lib/destination/firestore/config/validator/firestore_destination_validator.dart
metrics/ci_integrations/lib/destination/firestore/config/validator_factory/firestore_destination_validator_factory.dart
metrics/ci_integrations/lib/destination/firestore/party/firestore_destination_party.dart
metrics/ci_integrations/lib/destination/firestore/strings/firestore_strings.dart
metrics/ci_integrations/test/destination/firestore/config/model/firestore_destination_config_field_test.dart
metrics/ci_integrations/test/destination/firestore/config/validator/firestore_destination_validator_test.dart
metrics/ci_integrations/test/destination/firestore/config/validator_factory/firestore_destination_validator_factory_test.dart
metrics/ci_integrations/test/destination/firestore/party/firestore_destination_party_test.dart

feat: Implement Firestore DestinationConfigValidator and DestinationConfigValidatorFactory

---

metrics/web/lib/dashboard/domain/usecases/receive_project_metrics_updates.dart
metrics/web/test/dashboard/domain/usecases/receive_project_metrics_updates_test.dart

feat: Update Performance and Stability metrics calculation

---

metrics/cli/lib/sentry/cli/sentry_cli.dart
metrics/cli/lib/sentry/model/sentry_project.dart
metrics/cli/test/sentry/model/sentry_project_test.dart

feat: Implement SentryCLI

---

metrics/ci_integrations/lib/destination/firestore/factory/firebase_auth_factory.dart

fix: Fix Firebase Auth Initialization

---

metrics/ci_integrations/lib/client/jenkins/jenkins_client.dart
metrics/ci_integrations/lib/client/jenkins/model/jenkins_instance_info.dart
metrics/ci_integrations/test/client/jenkins/model/jenkins_instance_info_test.dart

fix: Fix Jenkins Url Validation

---

metrics/web/lib/dashboard/presentation/state/project_metrics_notifier.dart
metrics/web/lib/dashboard/presentation/view_models/build_result_metric_view_model.dart
metrics/web/lib/dashboard/presentation/view_models/build_result_view_model.dart
metrics/web/lib/dashboard/presentation/view_models/finished_build_result_view_model.dart
metrics/web/lib/dashboard/presentation/view_models/in_progress_build_result_view_model.dart
metrics/web/lib/dashboard/presentation/widgets/build_result_bar_graph.dart
metrics/web/test/dashboard/presentation/state/project_metrics_notifier_test.dart
metrics/web/test/dashboard/presentation/view_models/build_result_metric_view_model_test.dart
metrics/web/test/dashboard/presentation/view_models/build_result_view_model_test.dart
metrics/web/test/dashboard/presentation/view_models/finished_build_result_view_model_test.dart
metrics/web/test/dashboard/presentation/view_models/in_progress_build_result_view_model_test.dart
metrics/web/test/dashboard/presentation/widgets/build_result_bar_graph_test.dart
metrics/web/test/dashboard/presentation/widgets/build_result_bar_test.dart
metrics/web/test/dashboard/presentation/widgets/strategy/build_result_bar_padding_strategy_test.dart

feat: Implement view models for finished and in-progress builds

---

metrics/web/lib/dashboard/presentation/view_models/build_result_popup_view_model.dart
metrics/web/lib/dashboard/presentation/widgets/build_result_popup_card.dart
metrics/web/test/dashboard/presentation/view_models/build_result_popup_view_model_test.dart
metrics/web/test/dashboard/presentation/widgets/build_result_popup_card_test.dart

feat: Update BuildResultPopupCard and ViewModel

---

metrics/cli/lib/common/factory/services_factory.dart
metrics/cli/lib/common/model/services.dart
metrics/cli/test/common/factory/services_factory_test.dart
metrics/cli/test/common/model/services_test.dart

feat: Implement ServicesFactory

---

metrics/web/lib/dashboard/presentation/widgets/strategy/build_result_duration_strategy.dart
metrics/web/test/dashboard/presentation/widgets/strategy/build_result_duration_strategy_test.dart

feat: Implement BuildResultDurationStrategy

---

metrics/web/lib/dashboard/presentation/state/project_metrics_notifier.dart
metrics/web/lib/dashboard/presentation/view_models/build_result_metric_view_model.dart
metrics/web/test/dashboard/presentation/state/project_metrics_notifier_test.dart
metrics/web/test/dashboard/presentation/view_models/build_result_metric_view_model_test.dart

feat: Update BuildResultViewModel mapping

---

metrics/cli/lib/cli/firebase/firebase_command.dart
metrics/cli/lib/common/factory/services_factory.dart
metrics/cli/lib/deploy/constants/deploy_constants.dart
metrics/cli/lib/deploy/deployer.dart
metrics/cli/lib/deploy/factory/deployer_factory.dart
metrics/cli/lib/firebase/cli/firebase_cli.dart
metrics/cli/lib/gcloud/adapter/gcloud_cli_service_adapter.dart
metrics/cli/lib/gcloud/cli/gcloud_cli.dart
metrics/cli/test/common/factory/services_factory_test.dart
metrics/cli/test/common/model/services_test.dart
metrics/cli/test/deploy/deployer_dart_test.dart
metrics/cli/test/deploy/deployer_test.dart
metrics/cli/test/deploy/factory/deployer_factory_test.dart
metrics/cli/test/flutter/adapter/flutter_cli_service_adapter_test.dart
metrics/cli/test/gcloud/adapter/gcloud_cli_service_adapter_test.dart
metrics/cli/test/helper/file_helper_test.dart
metrics/cli/test/test_utils/directory_mock.dart
metrics/cli/test/test_utils/flutter_service_mock.dart
metrics/cli/test/test_utils/gcloud_service_mock.dart

feat: Implement Deployer

---

metrics/web/pubspec.yaml

fix: Fix package versions conflict on the latest master

---

metrics/web/docs/features/in_progress_builds/01_in_progress_builds_introduction.md
metrics/web/docs/features/in_progress_builds/diagrams/presentation_layer_strategies_class_diagram.puml
metrics/web/lib/base/presentation/graphs/bar_graph.dart
metrics/web/lib/dashboard/presentation/widgets/build_result_bar_graph.dart
metrics/web/lib/dashboard/presentation/widgets/build_results_metric_graph.dart
metrics/web/lib/dashboard/presentation/widgets/project_metrics_tile.dart
metrics/web/lib/dashboard/presentation/widgets/strategy/build_result_duration_strategy.dart
metrics/web/test/base/presentation/graphs/bar_graph_test.dart
metrics/web/test/dashboard/presentation/widgets/build_result_bar_graph_test.dart
metrics/web/test/dashboard/presentation/widgets/build_results_metric_graph_test.dart
metrics/web/test/dashboard/presentation/widgets/metrics_table_test.dart
metrics/web/test/dashboard/presentation/widgets/project_metrics_tile_test.dart
metrics/web/test/dashboard/presentation/widgets/strategy/build_result_duration_strategy_test.dart

feat: Implement BuildResultsMetricGraph

---

docs/16_dependencies_licenses.md
metrics/cli/bin/main.dart
metrics/cli/lib/deploy/deploy_command.dart
metrics/cli/lib/runner/metrics_cli_runner.dart
metrics/cli/pubspec.yaml
metrics/cli/test/deploy/deploy_command_test.dart
metrics/cli/test/runner/metrics_cli_runner_test.dart

feat: Implement MetricsCliRunner

---

metrics/docs/03_using_dart_in_the_firebase_cloud_functions.md
metrics/firebase/docs/analysis/01_using_dart_in_the_firebase_cloud_functions.md

docs: Cloud Functions using Dart Analysis doc

---

metrics/cli/lib/common/factory/services_factory.dart
metrics/cli/lib/common/model/services.dart
metrics/cli/lib/deploy/constants/deploy_constants.dart
metrics/cli/lib/deploy/deployer.dart
metrics/cli/lib/doctor/doctor.dart
metrics/cli/lib/npm/adapter/npm_cli_service_adapter.dart
metrics/cli/lib/npm/service/npm_service.dart
metrics/cli/test/common/factory/services_factory_test.dart
metrics/cli/test/common/model/services_test.dart
metrics/cli/test/deploy/deployer_test.dart
metrics/cli/test/deploy/factory/deployer_factory_test.dart
metrics/cli/test/doctor/doctor_test.dart
metrics/cli/test/doctor/factory/doctor_factory_test.dart
metrics/cli/test/npm/adapter/npm_cli_service_adapter_test.dart
metrics/cli/test/test_utils/npm_service_mock.dart

feat: Implement NpmService

---

metrics/ci_integrations/lib/destination/firestore/adapter/firestore_destination_client_adapter.dart
metrics/ci_integrations/lib/integration/interface/destination/client/destination_client.dart
metrics/ci_integrations/lib/integration/interface/source/client/source_client.dart
metrics/ci_integrations/lib/source/buildkite/adapter/buildkite_source_client_adapter.dart
metrics/ci_integrations/lib/source/github_actions/adapter/github_actions_source_client_adapter.dart
metrics/ci_integrations/lib/source/jenkins/adapter/jenkins_source_client_adapter.dart
metrics/ci_integrations/test/destination/firestore/adapter/firestore_destination_client_adapter_test.dart
metrics/ci_integrations/test/integration/ci/test_utils/stub/destination_client_stub.dart
metrics/ci_integrations/test/integration/ci/test_utils/stub/source_client_stub.dart
metrics/ci_integrations/test/source/buildkite/adapter/buildkite_source_client_adapter_test.dart
metrics/ci_integrations/test/source/github_actions/adapter/github_actions_source_client_adapter_test.dart
metrics/ci_integrations/test/source/jenkins/adapter/jenkins_source_client_adapter_test.dart

feat: Update the SourceClient and DestinationClient interfaces

---

metrics/firebase/docs/analysis/02_firebase_metrics_aggregation.md

docs: Firebase aggregation analysis document

---

metrics/ci_integrations/lib/client/buildkite/buildkite_client.dart
metrics/ci_integrations/lib/client/jenkins/jenkins_client.dart
metrics/ci_integrations/test/client/buildkite/buildkite_client_test.dart
metrics/ci_integrations/test/client/firestore/firestore_test.dart
metrics/ci_integrations/test/client/jenkins/jenkins_client_test.dart
metrics/ci_integrations/test/client/jenkins/test_utils/mock/jenkins_mock_server.dart
metrics/ci_integrations/test/test_utils/matchers.dart

feat: Extend the JenkinsClient to include the `fetchBuildByNumber` method

---

metrics/ci_integrations/lib/integration/ci/sync_stage/builds/builds_sync_stage.dart
metrics/ci_integrations/lib/integration/ci/sync_stage/sync_stage.dart
metrics/ci_integrations/test/integration/ci/sync_stage/builds/builds_sync_stage_test.dart

feat: Implement `SyncStage`, `BuildsSyncStage`

---

metrics/ci_integrations/lib/source/jenkins/adapter/jenkins_source_client_adapter.dart
metrics/ci_integrations/test/source/jenkins/adapter/jenkins_source_client_adapter_test.dart

feat: Implement `.fetchOneBuild` in the JenkinsSourceClientAdapter

---

metrics/ci_integrations/lib/source/github_actions/adapter/github_actions_source_client_adapter.dart
metrics/ci_integrations/test/source/github_actions/adapter/github_actions_source_client_adapter_test.dart

feat: Implement `.fetchOneBuild()` in the GithubActionsSourceClientAdapter

---

metrics/ci_integrations/test/integration/ci/sync_stage/builds/new_builds_sync_stage_test.dart

fix: Fix matchers in NewBuildsSyncStage tests

---

metrics/firebase/firestore/rules/firestore.rules
metrics/firebase/test/firestore/rules/tasks-test.js
metrics/firebase/test/firestore/rules/test_utils/test-data.js

feat: Implement security rules for the “tasks” collection

---

metrics/firebase/firestore/rules/firestore.rules
metrics/firebase/test/firestore/rules/build-days-test.js
metrics/firebase/test/firestore/rules/test_utils/test-data.js

feat: Implement security rules for the “build_days” collection

---

metrics/ci_integrations/lib/data/deserializer/build_data_deserializer.dart
metrics/ci_integrations/test/data/deserializer/build_data_deserializer_test.dart
metrics/web/lib/dashboard/data/deserializer/build_data_deserializer.dart
metrics/web/test/dashboard/data/deserializer/build_data_deserializer_test.dart

fix: Update BuildData deserialization

---

metrics/web/docs/features/builds_aggregation/01_builds_aggregation_design.md
metrics/web/docs/features/builds_aggregation/diagrams/build_days_data_layer_class_diagram.puml
metrics/web/docs/features/builds_aggregation/diagrams/build_days_domain_layer_class_diagram.puml
metrics/web/docs/features/builds_aggregation/diagrams/build_days_presentation_layer_class_diagram.puml
metrics/web/docs/features/builds_aggregation/diagrams/build_days_sequence_diagram.puml

docs: Metrics Web Application builds aggregation design document

---

metrics/cli/lib/firebase/cli/firebase_cli.dart
metrics/cli/lib/gcloud/cli/gcloud_cli.dart

fix: [Metrics CLI] Improve login methods

---

metrics/cli/lib/deploy/deployer.dart
metrics/cli/lib/gcloud/adapter/gcloud_cli_service_adapter.dart
metrics/cli/lib/gcloud/service/gcloud_service.dart
metrics/cli/lib/gcloud/strings/gcloud_strings.dart
metrics/cli/test/deploy/deployer_test.dart
metrics/cli/test/gcloud/adapter/gcloud_cli_service_adapter_test.dart

feat: Add accept terms method to the GCloudService

---

metrics/ci_integrations/lib/source/jenkins/adapter/jenkins_source_client_adapter.dart
metrics/ci_integrations/test/source/jenkins/adapter/jenkins_source_client_adapter_test.dart

feat: Update JenkinsSourceClientAdapter in-progress builds mapping

---

metrics/ci_integrations/lib/client/buildkite/buildkite_client.dart
metrics/ci_integrations/lib/source/buildkite/adapter/buildkite_source_client_adapter.dart
metrics/ci_integrations/lib/util/url/url_utils.dart
metrics/ci_integrations/test/client/buildkite/buildkite_client_test.dart
metrics/ci_integrations/test/client/buildkite/test_utils/mock/buildkite_mock_server.dart
metrics/ci_integrations/test/source/buildkite/adapter/buildkite_source_client_adapter_test.dart
metrics/ci_integrations/test/source/buildkite/test_utils/test_data/buildkite_test_data_generator.dart
metrics/ci_integrations/test/util/url/url_utils_test.dart

feat: Update BuildkiteSourceClientAdapter in-progress builds mapping

---

metrics/ci_integrations/docs/features/in_progress_builds/in_progress_builds_introduction.md
metrics/ci_integrations/lib/source/github_actions/adapter/github_actions_source_client_adapter.dart
metrics/ci_integrations/test/source/github_actions/adapter/github_actions_source_client_adapter_test.dart
metrics/ci_integrations/test/source/github_actions/test_utils/test_data/github_actions_test_data_generator.dart

feat: Update GithubActionsSourceClientAdapter in-progress builds mapping

---

metrics/web/lib/common/domain/entities/build_day.dart
metrics/web/lib/common/domain/repositories/build_day_repository.dart
metrics/web/lib/dashboard/domain/entities/metrics/build_day_project_metrics.dart
metrics/web/lib/dashboard/domain/entities/metrics/build_performance.dart
metrics/web/lib/dashboard/domain/entities/metrics/dashboard_project_metrics.dart
metrics/web/lib/dashboard/domain/entities/metrics/performance_metric.dart
metrics/web/lib/dashboard/domain/usecases/receive_build_day_project_metrics_updates.dart
metrics/web/test/common/domain/entities/build_day_test.dart
metrics/web/test/dashboard/domain/entities/metrics/build_day_project_metrics_test.dart
metrics/web/test/dashboard/domain/entities/metrics/build_performance_test.dart
metrics/web/test/dashboard/domain/entities/metrics/performance_metric_test.dart
metrics/web/test/dashboard/domain/entities/metrics/receive_build_day_project_metrics_updates_test.dart
metrics/web/test/dashboard/domain/usecases/receive_build_day_project_metrics_updates_test.dart

feat: Builds aggregation - Domain Layer

---

metrics/firebase/docs/analysis/02_firebase_metrics_aggregation.md

chore: reword decision section to simplify reading

---

metrics/cli/bin/main.dart

fix: Fix error handling in main.dart 

---

concept_map.puml
readme.md

docs: Update concept map to include all Metrics components

---

metrics/cli/lib/deploy/deployer.dart
metrics/cli/lib/gcloud/adapter/gcloud_cli_service_adapter.dart
metrics/cli/lib/gcloud/service/gcloud_service.dart
metrics/cli/lib/gcloud/strings/gcloud_strings.dart
metrics/cli/test/deploy/deployer_test.dart
metrics/cli/test/gcloud/adapter/gcloud_cli_service_adapter_test.dart
metrics/cli/test/gcloud/strings/gcloud_strings_test.dart

feat: Add the user prompt to explain how to set up the Oauth 2.0 authorized JavaScript origins

---

metrics/cli/lib/deploy/constants/deploy_constants.dart
metrics/cli/lib/firebase/strings/firebase_strings.dart
metrics/cli/lib/gcloud/adapter/gcloud_cli_service_adapter.dart
metrics/cli/lib/gcloud/strings/gcloud_strings.dart
metrics/cli/test/gcloud/adapter/gcloud_cli_service_adapter_test.dart
metrics/firebase/functions/package.json

feat: Deployer improvements

---

metrics/firebase/functions/pubspec.yaml

fix: Update `Functions` package dependencies

---

.github/workflows/ci_integrations_actions.yml
.github/workflows/coverage_converter_actions.yml
.github/workflows/metrics_integration_actions.yml
.github/workflows/web_actions.yml

feat: Update Github Actions to sync the build data on start

---

metrics/cli/lib/deploy/command/deploy_command.dart
metrics/cli/lib/firebase/strings/firebase_strings.dart
metrics/cli/lib/gcloud/strings/gcloud_strings.dart
metrics/cli/lib/sentry/strings/sentry_strings.dart

feat: Improve Metrics CLI wording

---

metrics/firebase/firestore/indexes/firestore.indexes.json

feat: Update Firestore indexes

---

metrics/cli/lib/deploy/model/deploy_paths.dart

fix: Fix web app build path

---

metrics/cli/lib/deploy/deployer.dart
metrics/cli/lib/deploy/strings/deploy_strings.dart
metrics/cli/lib/gcloud/adapter/gcloud_cli_service_adapter.dart
metrics/cli/lib/gcloud/strings/gcloud_strings.dart
metrics/cli/lib/prompt/prompter.dart
metrics/cli/lib/prompt/writer/io_prompt_writer.dart
metrics/cli/lib/prompt/writer/prompt_writer.dart
metrics/cli/test/deploy/deployer_test.dart
metrics/cli/test/gcloud/adapter/gcloud_cli_service_adapter_test.dart
metrics/cli/test/prompt/prompter_test.dart
metrics/cli/test/prompt/writer/io_prompt_writer_test.dart

feat: Deployer prompt improvements

---

metrics/readme.md
readme.md

docs: Update top-level readme

---

metrics/docs/01_storing_database_metadata.md

docs: Fix `Metrics Web Supported Database Version` document reference

---

metrics/cli/lib/firebase/strings/firebase_strings.dart

fix: Fix enabling analytics steps 

---

metrics/cli/docs/05_user_manual_steps.md
metrics/cli/lib/sentry/strings/sentry_strings.dart

fix: Fix Sentry enter release name string

---

.github/workflows/cli_actions.yml

fix: Fix tag name in the cli_actions

---

metrics/cli/lib/gcloud/adapter/gcloud_cli_service_adapter.dart
metrics/cli/lib/gcloud/cli/gcloud_cli.dart
metrics/cli/lib/gcloud/service/gcloud_service.dart
metrics/cli/test/gcloud/adapter/gcloud_cli_service_adapter_test.dart

feat: Update GCloud CLI and Service to add delete project functionality

---

readme.md

fix: Fix top-level readme link

---

docs/13_firebase_deployment_cli.md
metrics/readme.md

docs: Update Metrics readme to include installation steps

---

docs/08_firebase_deployment.md
docs/13_firebase_deployment_cli.md
metrics/cli/README.md
metrics/cli/docs/01_metrics_cli_design.md

fix: Fix links

---

metrics/cli/lib/prompter/prompter.dart
metrics/cli/lib/prompter/writer/io_prompt_writer.dart
metrics/cli/lib/prompter/writer/prompt_writer.dart
metrics/cli/test/prompter/prompter_test.dart
metrics/cli/test/prompter/writer/io_prompt_writer_test.dart

feat: Add 'error' method to `Prompter`

---

metrics/cli/lib/cli/deployer/deployer.dart
metrics/cli/lib/cli/deployer/strings/deploy_strings.dart
metrics/cli/test/cli/deployer/deployer_test.dart

feat: Add `Deployer` error handling

---

metrics/readme.md

fix: Fix Metrics readme

---

metrics/cli/README.md

fix: Fix Metrics CLI readme

---

metrics/cli/lib/cli/deployer/deployer.dart
metrics/cli/lib/cli/deployer/strings/deploy_strings.dart
metrics/cli/test/cli/deployer/deployer_test.dart

feat: Delete the GCloud project on Deployer fail

---

docs/19_feature_design_template.md

Explain the Analysis section with subsections to simplify feature analysis in the future.

docs: Feature design template update

---

metrics/web/docs/features/storybook/01_create_metrics_storybook.md
metrics/web/docs/features/storybook/01_metrics_storybook_design.md
metrics/web/docs/features/storybook/diagrams/metrics_storybook_web_relation_diagram.puml

docs: Metrics storybook analysis document

---

metrics/web/docs/features/deep_links/01_deep_linking.md
metrics/web/docs/features/deep_links/diagrams/parsing_deep_links_class_diagram.puml

docs: Improve the deep links design document

---

metrics/web/docs/features/storybook/01_metrics_storybook_design.md
metrics/web/docs/features/storybook/diagrams/metrics_storybook_web_relation_diagram.puml

fix: Improve the Metrics Storybook analysis document

---

metrics/web/lib/common/presentation/metrics_app/metrics_app.dart
metrics/web/lib/common/presentation/navigation/metrics_route_information_parser.dart
metrics/web/lib/common/presentation/navigation/route_configuration/route_configuration.dart
metrics/web/lib/common/presentation/navigation/route_configuration/route_configuration_factory.dart
metrics/web/lib/common/presentation/navigation/route_configuration/route_configuration_location_converter.dart
metrics/web/test/common/presentation/navigation/metrics_route_information_parser_test.dart
metrics/web/test/common/presentation/navigation/route_configuration/route_configuration_factory_test.dart
metrics/web/test/common/presentation/navigation/route_configuration/route_configuration_location_converter_test.dart
metrics/web/test/common/presentation/navigation/route_configuration/route_configuration_test.dart

feat: Update the `RouteConfiguration` class to include the `parameters` field

---

metrics/cli/docs/features/doctor_output_improvements/06_doctor_output_improvements.md

docs: Fix diagram in "Doctor Output Improvements"

---

metrics/web/docs/features/deep_links/diagrams/applying_deep_links_sequence_diagram.puml
metrics/web/docs/features/deep_links/diagrams/updating_page_parameters_sequence_diagram.puml

docs: Improve diagrams in "Deep Linking" design doc

---

docs/19_feature_design_template.md

docs: add privacy and security sections to the feature template

---

metrics/cli/docs/features/update/diagrams/updater_class_diagram.puml
metrics/cli/lib/cli/deployer/deployer.dart
metrics/cli/lib/cli/deployer/factory/deployer_factory.dart
metrics/cli/lib/common/model/factory/paths_factory.dart
metrics/cli/lib/common/model/paths.dart
metrics/cli/lib/common/model/sentry_web_config.dart
metrics/cli/lib/common/model/web_metrics_config.dart
metrics/cli/lib/services/firebase/adapter/firebase_cli_service_adapter.dart
metrics/cli/lib/services/firebase/cli/firebase_cli.dart
metrics/cli/lib/services/firebase/firebase_service.dart
metrics/cli/lib/services/sentry/adapter/sentry_cli_service_adapter.dart
metrics/cli/lib/services/sentry/cli/sentry_cli.dart
metrics/cli/lib/services/sentry/sentry_service.dart
metrics/cli/test/cli/deployer/deployer_test.dart
metrics/cli/test/common/model/factory/paths_factory_test.dart
metrics/cli/test/common/model/paths_test.dart
metrics/cli/test/common/model/sentry_web_config_test.dart
metrics/cli/test/common/model/web_metrics_config_test.dart
metrics/cli/test/prompter/prompter_test.dart
metrics/cli/test/services/firebase/adapter/firebase_cli_service_adapter_test.dart
metrics/cli/test/services/gcloud/adapter/gcloud_cli_service_adapter_test.dart
metrics/cli/test/services/sentry/adapter/sentry_cli_service_adapter_test.dart

feat: Update cli services to add auth token parameters

---

metrics/cli/dependencies.yaml
metrics/cli/recommended_versions.yaml

feat: Update recommended_versions.yaml

---

metrics/web/lib/common/presentation/navigation/models/page_parameters_model.dart
metrics/web/lib/dashboard/presentation/models/dashboard_page_parameters_model.dart
metrics/web/test/dashboard/presentation/models/dashboard_page_parameters_model_test.dart

feat: Implement DashboardPageParametersModel

---

metrics/web/lib/common/presentation/injector/widget/injection_container.dart
metrics/web/lib/common/presentation/navigation/models/factory/page_parameters_factory.dart
metrics/web/lib/common/presentation/navigation/state/navigation_notifier.dart
metrics/web/test/common/presentation/navigation/metrics_page/metrics_page_factory_test.dart
metrics/web/test/common/presentation/navigation/metrics_router_delegate_test.dart
metrics/web/test/common/presentation/navigation/models/factory/page_parameters_factory_test.dart
metrics/web/test/common/presentation/navigation/state/navigation_notifier_test.dart
metrics/web/test/test_utils/route_name_mock.dart

feat: Implement Page Parameters Factory

---

metrics/cli/lib/services/common/auth_service.dart
metrics/cli/lib/services/common/cli/auth_cli.dart
metrics/cli/lib/services/common/mixin/authorization.dart
metrics/cli/lib/services/firebase/adapter/firebase_cli_service_adapter.dart
metrics/cli/lib/services/firebase/cli/firebase_cli.dart
metrics/cli/lib/services/firebase/firebase_service.dart
metrics/cli/lib/services/sentry/adapter/sentry_cli_service_adapter.dart
metrics/cli/lib/services/sentry/cli/sentry_cli.dart
metrics/cli/lib/services/sentry/sentry_service.dart
metrics/cli/test/common/model/paths/paths_test.dart
metrics/cli/test/common/strings/common_strings_test.dart
metrics/cli/test/services/common/auth_cli_test.dart
metrics/cli/test/services/firebase/adapter/firebase_cli_service_adapter_test.dart
metrics/cli/test/services/firebase/strings/firebase_strings_test.dart
metrics/cli/test/services/gcloud/adapter/gcloud_cli_service_adapter_test.dart
metrics/cli/test/services/gcloud/strings/gcloud_strings_test.dart
metrics/cli/test/services/git/adapter/git_cli_service_adapter_test.dart
metrics/cli/test/services/npm/adapter/npm_cli_service_adapter_test.dart
metrics/cli/test/services/sentry/adapter/sentry_cli_service_adapter_test.dart
metrics/cli/test/services/sentry/strings/sentry_strings_test.dart

feat: Add an ability to set the auth token for the whole CLI class

---

metrics/core/lib/src/util/validation/validation_conclusion.dart
metrics/core/lib/src/util/validation/validation_target.dart
metrics/core/pubspec.yaml
metrics/core/test/util/validation/validation_conclusion_test.dart
metrics/core/test/util/validation/validation_target_test.dart

feat: Implement ValidationConclusion and ValidationTarget

---

metrics/core/lib/src/util/validation/validation_result.dart
metrics/core/lib/src/util/validation/validation_result_builder.dart
metrics/core/test/util/validation/validation_result_builder_test.dart
metrics/core/test/util/validation/validation_result_test.dart

feat: Implement ValidationResult and ValidationResultBuilder

---

metrics/web/lib/common/presentation/navigation/metrics_page/metrics_page.dart
metrics/web/lib/common/presentation/navigation/metrics_page/metrics_page_factory.dart
metrics/web/lib/common/presentation/navigation/state/navigation_notifier.dart
metrics/web/lib/dashboard/presentation/pages/dashboard_page.dart
metrics/web/lib/project_groups/presentation/pages/project_group_page.dart
metrics/web/test/common/presentation/app_bar/widget/metrics_app_bar_test.dart
metrics/web/test/common/presentation/navigation/metrics_page/metrics_page_factory_test.dart
metrics/web/test/common/presentation/navigation/metrics_page/metrics_page_test.dart
metrics/web/test/common/presentation/navigation/metrics_router_delegate_test.dart
metrics/web/test/common/presentation/navigation/state/navigation_notifier_test.dart
metrics/web/test/dashboard/presentation/page/dashboard_page_test.dart
metrics/web/test/project_groups/presentation/pages/project_group_page_test.dart

feat: Metrics page updates

---

metrics/web/lib/common/presentation/navigation/state/navigation_notifier.dart
metrics/web/lib/common/presentation/page_title/widgets/metrics_page_title.dart
metrics/web/test/common/presentation/navigation/state/navigation_notifier_test.dart
metrics/web/test/common/presentation/page_title/widgets/metrics_page_title_test.dart

feat: Improve navigate back functionality

---

metrics/cli/lib/cli/command/deploy_command.dart
metrics/cli/lib/cli/command/doctor_command.dart
metrics/cli/lib/cli/command/update_command.dart
metrics/cli/lib/cli/runner/metrics_cli_runner.dart
metrics/cli/lib/cli/updater/config/factory/update_config_factory.dart
metrics/cli/test/cli/command/deploy_command_test.dart
metrics/cli/test/cli/command/update_command_test.dart
metrics/cli/test/cli/runner/metrics_cli_runner_test.dart
metrics/cli/test/cli/updater/config/factory/update_config_factory_test.dart
metrics/cli/test/cli/updater/updater_test.dart
metrics/cli/test/test_utils/mocks/update_config_mock.dart

feat: Implement Update command

---

metrics/web/lib/common/presentation/injector/widget/injection_container.dart
metrics/web/lib/common/presentation/navigation/route_configuration/metrics_page_route_configuration_factory.dart
metrics/web/lib/common/presentation/navigation/state/navigation_notifier.dart
metrics/web/test/common/presentation/navigation/metrics_router_delegate_test.dart
metrics/web/test/common/presentation/navigation/route_configuration/metrics_page_route_configuration_factory_test.dart
metrics/web/test/common/presentation/navigation/state/navigation_notifier_test.dart

feat: Implement metrics page route configuration factory

---

metrics/ci_integrations/lib/integration/stub/base/config/validation_delegate/validation_delegate_stub.dart
metrics/ci_integrations/lib/integration/stub/base/config/validator/config_validator_stub.dart
metrics/ci_integrations/lib/integration/stub/base/config/validator_factory/config_validator_factory_stub.dart
metrics/ci_integrations/test/integration/stub/base/config/validator/config_validator_stub_test.dart
metrics/ci_integrations/test/integration/stub/base/config/validator_factory/config_validator_factory_stub_test.dart

feat: Create stubs for CI Integration's validation

---

metrics/cli/lib/util/dependencies/dependency.dart
metrics/cli/test/util/dependencies/dependency_test.dart

feat: Implement the Dependency model

---

metrics/ci_integrations/lib/cli/command/validate_command.dart
metrics/ci_integrations/lib/destination/firestore/config/validator/firestore_destination_validator.dart
metrics/ci_integrations/lib/destination/firestore/config/validator_factory/firestore_destination_validator_factory.dart
metrics/ci_integrations/lib/destination/firestore/party/firestore_destination_party.dart
metrics/ci_integrations/lib/integration/interface/base/config/validator/config_validator.dart
metrics/ci_integrations/lib/integration/stub/base/config/validator/validator_stub.dart
metrics/ci_integrations/lib/integration/stub/base/config/validator_factory/validator_factory_stub.dart
metrics/ci_integrations/lib/integration/validation/model/config_field_validation_conclusion.dart
metrics/ci_integrations/lib/source/buildkite/config/validator/buildkite_source_validator.dart
metrics/ci_integrations/lib/source/buildkite/config/validator_factory/buildkite_source_validator_factory.dart
metrics/ci_integrations/lib/source/buildkite/party/buildkite_source_party.dart
metrics/ci_integrations/lib/source/github_actions/config/validator/github_actions_source_validator.dart
metrics/ci_integrations/lib/source/github_actions/config/validator_factory/github_actions_source_validator_factory.dart
metrics/ci_integrations/lib/source/github_actions/party/github_actions_source_party.dart
metrics/ci_integrations/lib/source/jenkins/config/validator/jenkins_source_validator.dart
metrics/ci_integrations/lib/source/jenkins/config/validator_factory/jenkins_source_validator_factory.dart
metrics/ci_integrations/lib/source/jenkins/party/jenkins_source_party.dart
metrics/ci_integrations/test/cli/command/validate_command_test.dart
metrics/ci_integrations/test/destination/firestore/party/firestore_destination_party_test.dart
metrics/ci_integrations/test/integration/stub/base/config/validator/validator_stub_test.dart
metrics/ci_integrations/test/integration/stub/base/config/validator_factory/validator_factory_stub_test.dart
metrics/ci_integrations/test/source/buildkite/party/buildkite_source_party_test.dart
metrics/ci_integrations/test/source/github_actions/party/github_actions_source_party_test.dart
metrics/ci_integrations/test/source/jenkins/party/jenkins_source_party_test.dart

feat: Update ValidateCommand to use validation from Metrics Core

---

metrics/web/lib/common/presentation/injector/widget/injection_container.dart
metrics/web/lib/common/presentation/navigation/state/navigation_notifier.dart
metrics/web/test/common/presentation/navigation/metrics_router_delegate_test.dart
metrics/web/test/common/presentation/navigation/state/navigation_notifier_test.dart

feat: Add a handlePageParametersUpdates method to the NavigationNotifier

---

metrics/cli/lib/util/dependencies/dependencies.dart
metrics/cli/lib/util/dependencies/factory/dependencies_factory.dart
metrics/cli/test/util/dependencies/dependencies_test.dart
metrics/cli/test/util/dependencies/factory/dependencies_factory_test.dart

feat: Implement Dependencies and DependenciesFactory 

---

metrics/core/lib/src/util/validation/validation_result_builder.dart
metrics/core/test/util/validation/validation_result_builder_test.dart

fix: Fix ValidationResultBuilder

---

metrics/cli/lib/services/common/info_service.dart
metrics/cli/lib/services/firebase/adapter/firebase_cli_service_adapter.dart
metrics/cli/lib/services/firebase/firebase_service.dart
metrics/cli/lib/services/flutter/adapter/flutter_cli_service_adapter.dart
metrics/cli/lib/services/flutter/flutter_service.dart
metrics/cli/lib/services/gcloud/adapter/gcloud_cli_service_adapter.dart
metrics/cli/lib/services/gcloud/gcloud_service.dart
metrics/cli/lib/services/git/adapter/git_cli_service_adapter.dart
metrics/cli/lib/services/git/git_service.dart
metrics/cli/lib/services/npm/adapter/npm_cli_service_adapter.dart
metrics/cli/lib/services/npm/npm_service.dart
metrics/cli/lib/services/sentry/adapter/sentry_cli_service_adapter.dart
metrics/cli/lib/services/sentry/sentry_service.dart

feat: Update services to include ServiceName

---

metrics/cli/lib/cli/doctor/doctor.dart
metrics/cli/lib/services/common/info_service.dart
metrics/cli/lib/services/firebase/adapter/firebase_cli_service_adapter.dart
metrics/cli/lib/services/firebase/cli/firebase_cli.dart
metrics/cli/lib/services/flutter/adapter/flutter_cli_service_adapter.dart
metrics/cli/lib/services/flutter/cli/flutter_cli.dart
metrics/cli/lib/services/gcloud/adapter/gcloud_cli_service_adapter.dart
metrics/cli/lib/services/gcloud/cli/gcloud_cli.dart
metrics/cli/lib/services/git/adapter/git_cli_service_adapter.dart
metrics/cli/lib/services/git/cli/git_cli.dart
metrics/cli/lib/services/npm/adapter/npm_cli_service_adapter.dart
metrics/cli/lib/services/npm/cli/npm_cli.dart
metrics/cli/lib/services/sentry/adapter/sentry_cli_service_adapter.dart
metrics/cli/lib/services/sentry/cli/sentry_cli.dart
metrics/cli/test/cli/doctor/doctor_test.dart
metrics/cli/test/services/firebase/adapter/firebase_cli_service_adapter_test.dart
metrics/cli/test/services/flutter/adapter/flutter_cli_service_adapter_test.dart
metrics/cli/test/services/gcloud/adapter/gcloud_cli_service_adapter_test.dart
metrics/cli/test/services/git/adapter/git_cli_service_adapter_test.dart
metrics/cli/test/services/npm/adapter/npm_cli_service_adapter_test.dart
metrics/cli/test/services/sentry/adapter/sentry_cli_service_adapter_test.dart

feat: Update services' version checking

---

metrics/web/lib/auth/presentation/pages/login_page.dart
metrics/web/lib/common/presentation/injector/widget/injection_container.dart
metrics/web/lib/common/presentation/navigation/state/navigation_notifier.dart
metrics/web/lib/common/presentation/pages/loading_page.dart
metrics/web/test/auth/presentation/pages/login_page_test.dart
metrics/web/test/common/presentation/navigation/state/navigation_notifier_test.dart
metrics/web/test/common/presentation/pages/loading_page_test.dart

feat: Handling deep links that require authorization

---

metrics/cli/lib/cli/doctor/constants/doctor_constants.dart
metrics/cli/lib/cli/doctor/doctor.dart
metrics/cli/lib/cli/doctor/factory/doctor_factory.dart
metrics/cli/test/cli/doctor/doctor_test.dart
metrics/cli/test/cli/doctor/factory/doctor_factory_test.dart
metrics/cli/test/test_utils/mocks/dependencies_factory_mock.dart
metrics/cli/test/test_utils/mocks/dependencies_mock.dart

feat: Update Doctor with Dependencies

---

.github/workflows/web_actions.yml

fix: Build skia app using the current Flutter version

---

metrics/web/lib/common/presentation/manufacturer_banner/theme/theme_data/manufaacturer_banner_theme_data.dart
metrics/web/lib/common/presentation/manufacturer_banner/theme/theme_data/manufacturer_banner_theme_data.dart
metrics/web/lib/common/presentation/metrics_app/metrics_app.dart
metrics/web/lib/common/presentation/metrics_theme/config/metrics_colors.dart
metrics/web/lib/common/presentation/metrics_theme/config/text_style_config.dart
metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
metrics/web/lib/common/presentation/metrics_theme/model/metrics_theme_data.dart
metrics/web/test/common/presentation/manufacturer_banner/theme/theme_data/manufacturer_banner_theme_data_test.dart
metrics/web/test/common/presentation/metrics_theme/model/dark_metrics_theme_data_test.dart
metrics/web/test/common/presentation/metrics_theme/model/light_metrics_theme_data_test.dart
metrics/web/test/common/presentation/metrics_theme/model/metrics_theme_data_test.dart

feat: ManufacturerBanner theme data

---

metrics/web/lib/feature_config/data/model/feature_config_data.dart
metrics/web/lib/feature_config/domain/entities/feature_config.dart
metrics/web/test/feature_config/data/model/feature_config_data_test.dart
metrics/web/test/feature_config/domain/entities/feature_config_test.dart

feat: Change the FeatureConfig entity and the FeatureConfigData model

---

metrics/web/lib/auth/data/repositories/firebase_user_repository.dart
metrics/web/lib/auth/domain/repositories/user_repository.dart

feat: Add the sign-in anonymously feature to the FirebaseUserRepository 

---

metrics/web/lib/feature_config/domain/usecases/fetch_feature_config_usecase.dart
metrics/web/lib/feature_config/domain/usecases/parameters/feature_config_param.dart
metrics/web/lib/feature_config/presentation/models/public_dashboard_feature_config_model.dart
metrics/web/lib/feature_config/presentation/state/feature_config_notifier.dart
metrics/web/test/feature_config/domain/usecases/fetch_feature_config_usecase_test.dart
metrics/web/test/feature_config/domain/usecases/parameters/feature_config_param_test.dart
metrics/web/test/feature_config/presentation/models/public_dashboard_feature_config_model_test.dart
metrics/web/test/feature_config/presentation/state/feature_config_notifier_test.dart
metrics/web/test/test_utils/feature_config_notifier_stub.dart

feat: Change the Presentation layer of the FeatureConfig module #1554

---

metrics/web/lib/auth/data/adapter/firebase_user_adapter.dart
metrics/web/lib/auth/domain/entities/user.dart
metrics/web/lib/auth/presentation/models/auth_state.dart
metrics/web/lib/auth/presentation/state/auth_notifier.dart
metrics/web/test/auth/data/adapter/firebase_user_adapter_test.dart
metrics/web/test/auth/domain/entities/user_test.dart
metrics/web/test/auth/presentation/state/auth_notifier_test.dart
metrics/web/test/test_utils/auth_notifier_stub.dart
metrics/web/test/test_utils/signed_in_auth_notifier_stub.dart

feat: Implement AuthState enum and integrate it

---

metrics/web/lib/auth/presentation/pages/login_page.dart

fix: Fix login screen overflow

---

metrics/web/lib/auth/presentation/pages/login_page.dart

fix: Fix login page scroll #1576

---

metrics/web/lib/auth/presentation/state/auth_notifier.dart
metrics/web/lib/common/presentation/injector/widget/injection_container.dart
metrics/web/lib/feature_config/presentation/state/feature_config_notifier.dart
metrics/web/test/common/presentation/injector/widget/injection_container_test.dart
metrics/web/test/test_utils/auth_notifier_stub.dart
metrics/web/test/test_utils/signed_in_auth_notifier_stub.dart

feat: Subscribe AuthNotifier on the FeatureConfig updates

---

metrics/web/lib/auth/domain/usecases/sign_in_anonymously_usecase.dart
metrics/web/test/auth/domain/usercases/sign_in_anonymously_usecase_test.dart

feat: Implement the use case class for the anonymous sign-in

---

metrics/firebase/firestore/rules/firestore.rules
metrics/firebase/test/firestore/rules/projects-test.js

feat: Update firestore security rules of project collection

---

metrics/firebase/test/firestore/rules/project-groups-test.js
metrics/firebase/test/firestore/rules/projects-test.js

fix: Fix merged firebase rules tests

---

metrics/web/lib/auth/presentation/state/auth_notifier.dart
metrics/web/lib/common/presentation/pages/loading_page.dart
metrics/web/test/auth/presentation/state/auth_notifier_test.dart
metrics/web/test/common/presentation/pages/loading_page_test.dart
metrics/web/test/test_utils/auth_notifier_stub.dart
metrics/web/test/test_utils/signed_in_auth_notifier_stub.dart

feat: Add the isInitialized getter to the AuthNotifier

---

metrics/firebase/firestore/rules/firestore.rules
metrics/firebase/test/firestore/rules/builds-test.js

feat: Update firestore security rules of builds collection

---

metrics/firebase/firestore/rules/firestore.rules
metrics/firebase/test/firestore/rules/build-days-test.js

feat: Update build days collection security rules 

---

metrics/firebase/firestore/rules/firestore.rules
metrics/firebase/test/firestore/rules/allowed-email-domains-test.js
metrics/firebase/test/firestore/rules/feature-config-test.js
metrics/firebase/test/firestore/rules/tasks-test.js

refactor: Refactor firestore.rules

---

metrics/web/lib/auth/presentation/state/auth_notifier.dart
metrics/web/lib/auth/presentation/view_models/user_profile_view_model.dart
metrics/web/lib/common/presentation/strings/common_strings.dart
metrics/web/lib/common/presentation/widgets/metrics_user_menu.dart
metrics/web/test/auth/presentation/view_models/user_profile_view_model_test.dart
metrics/web/test/common/presentation/widgets/metrics_user_menu_test.dart
metrics/web/test/test_utils/auth_notifier_stub.dart
metrics/web/test/test_utils/signed_in_auth_notifier_stub.dart

feat: Change the MetricsUserMenu UI depending on the user authentication state

---

metrics/web/lib/common/presentation/navigation/state/navigation_notifier.dart
metrics/web/test_driver/app_test.dart

fix: Fix deep links with anonymous user login
